### ISSUE TITLE
Added New Scenario

### ISSUE THREAD

**Issue by slycozzolino** [NPBruce/valkyrie#770] opened 2018-03-19 18:22 UTC
I have added a new scenario. I have uploaded the package files to the link below.
https://github.com/slycozzolino/valkyrie-store/tree/master/MoM/A%20Glimpse%20of%20the%20Past

**Comment by NPBruce** [comment] 2018-03-19 22:02
Because of internet, the spaces will need to be removed from the directory and file names, then I can add this.

**Comment by scrubbless** [comment] 2018-03-20 08:34
Awesome look forward to playing it. The catalog of scenarios is getting quite large now.

**Comment by slycozzolino** [comment] 2018-03-20 17:09
Spaces removed.

**Comment by scrubbless** [comment] 2018-03-20 18:14
Replaced them with underscores.

To save you some detective work @NPBruce the new URL is:
https://github.com/slycozzolino/valkyrie-store/tree/master/MoM/A_Glimpse_of_the_Past

**Comment by NPBruce** [comment] 2018-03-20 21:05
Added, I will test when I am at a computer that can do so.

**Comment by scrubbless** [comment] 2018-03-20 22:47
Not showing in 1.7.0c on Android.

**Comment by NPBruce** [comment] 2018-03-21 08:06
Should be fixed now.

**Closed** 2018-03-21 08:06 UTC

**Comment by FASTNAVi** [comment] 2018-04-03 12:03
Hi! I just recently finish this your scenario and I want to report possible mistakes.

Several times you have missing action sign on door tokens. You have there only "continue" so it does not cost an action.

If you have an item, in this case ritual dagger, you can anytime use trade action and drop that item. Then you have every single turn test connected with that dagger, but what to do if the dagger is on the ground? Maybe add button with "anybody have the ritual dagger".. just suggestion =)

Thanks for your scenario!

**Comment by slycozzolino** [comment] 2018-04-05 19:44
Thanks for playing @FASTNAVi. I have updated those explore tokens to be an action. After a couple plays we still missed it. 

As for the Dagger, it specifically says when you gain it that it can be traded but not dropped.

If you find anything else let me know. I hope you still enjoyed it despite the issues.

**Comment by FASTNAVi** [comment] 2018-04-08 19:49
Hi again! Just finnished your scenario and this time we won! And about the dagger you were right of course - sorry about it ;-)

Anyway, we spotted some issues (played in 2 players):

1) Big problem. We killed 2 cultists and the Collector. Later, we use fuse box and after darkness came we again met all dead enemies once more again during mythos phase. I think you just miss one variables to add.. easy to repair.

2) The maid attack us in bedroom. The problem was that she chose a investigator far far away. It was not logical. Maybe instead of name she should attack some investigator in the range...

3) The Collector spotted dead maid but not investigators in the same room? This was for us a little bit weird.

It was very close win so we enjoyed the game! Thank you very much!

**Comment by slycozzolino** [comment] 2018-04-08 21:53
Thanks for playing @FASTNAVi and helping to find these issues.

1. Fixed

2. Updated to attack closest investigator instead of a random one.

3. This one is iffy. The way I picture it is the collector is casually looking for her and once he sees her he runs back. He is completely moving into or through any rooms. I added some text stating the investigators hide in the corner of their room fearing he could find them. Do you think that will work?

**Comment by montseel** [comment] 2018-04-21 18:45
Just played the scenario once, and I found some (potential) issues. At the end of the message I'll mention the context I was playing in, in case it's relevant. 

1. I got many mythos phases where nothing happened (i.e. no monsters appeared and no horror skill checks were needed). In fact, all the mythos phases before the maid turned into a cultist were like this. I don't know if this was intended or not. I guess it is, considering the context, but it doesn't hurt to mention it.

2. At one point, one of the mythos phases generated an event with no text. It included a button to "resolve event". When I clicked it, the text that appeared was also empty. 
![screen shot 2018-04-21 at 12 48 56](https://user-images.githubusercontent.com/38591534/39087650-62cc18ee-45a4-11e8-81f3-5d3da436ad9e.png)

3. Almost all the characters', explore, interact, and search tokens were represented by the wrong symbol. It wasn't game-breaking, but it would look better if they were the right ones ;). Can this be some issue with Valkyrie? 
![screen shot 2018-04-21 at 11 11 48](https://user-images.githubusercontent.com/38591534/39087581-472d578e-45a3-11e8-8ca6-ab04c607d801.png)

4. Typo: "however" instead of "whoever". 
![screen shot 2018-04-21 at 11 46 24](https://user-images.githubusercontent.com/38591534/39087640-2eac6d5c-45a4-11e8-9442-900ca646b83c.png)

5. This one was the worst for me. Once the first Star Spawn appeared, for every mythos phase that took place afterwards, another Star Spawn appeared, reaching the number of 6 Star Spawns in play before one of my investigators died and I lost the game. The same text kept appearing every time, as if the lead cultist (can't remember the exact name right now) wasn't already dead. 
![screen shot 2018-04-21 at 12 49 29](https://user-images.githubusercontent.com/38591534/39087661-89b7b594-45a4-11e8-9266-f5e9c04168f6.png)
![screen shot 2018-04-21 at 13 38 56](https://user-images.githubusercontent.com/38591534/39087667-a3836c52-45a4-11e8-99d6-2b1299d4e8af.png)
![screen shot 2018-04-21 at 13 38 52](https://user-images.githubusercontent.com/38591534/39087669-a7d82928-45a4-11e8-8e4d-f9b9b9aa6538.png)

6. This is design-related. I found that the mythos phases were pretty brutal after the first Star Spawn appeared. I kept having to do tests which, if they failed, resulted in my investigators having to draw many horror cards. Both went insane. The items I was given to mitigate this weren't enough to keep the horror under control. Maybe I didn't play well enough or I was taking too long to finish the scenario, but I thought it was worth mentioning.

7. Another design-related comment. It was weird getting mythos effects which had no impact in the game while finding lots of weapons in the house. This led me to meta-gaming without meaning to. "Things will get nasty for sure", that's what I thought. However, I do understand that the story is what it is (not a criticism), finding objects requires a few turns and it makes sense, story-wise, for the enemies to appear at once. I don't have a suggestion for this one.

Context: Played two players - Jenny and Ashcan Pete. Had the 1st edition characters and monsters turned on, but not the tiles, since I just own the base game. The app's (Valkyrie) language was set in Spanish. During the game, I didn't kill the Collector before he killed the kidnapped girl. I also tampered with the fuse box after the killing (didn't find it earlier), and I perfomed an undo in the app to make sure which rooms were left in the dark after doing so.

BTW: 

> I added some text stating the investigators hide in the corner of their room fearing he could find them.

Was OK with me. I also like FASTNAVi's suggestion of the collector sending his minions to do the dirty work while he performs the ritual.

I also liked the voice over! 

Thanks for your work and I hope this helps!

**Comment by slycozzolino** [comment] 2018-04-21 21:32
1-3 I believe are Valkyrie defects specific to Mac. I can create a new ticket for those. It may also be related to the language option as this scenario hasn't been translated yet.
4. Fixed
5 and 6 are tied together and a bug. I just put in an update to fix this issue. 
7. No mythos events should be blank. I believe this is related to 1-3. This scenario is not really suppose to ramp up like it did for you. The creature spawn should have taken away those scenario specific mythos events.

As for the collector sending his minions, there are several outcomes to what he does based on how he finds the house when he arrives, that is indeed one of them.

**Comment by NPBruce** [comment] 2018-04-21 22:31
For 1-3 I would really like:

1: Version the scenario was saved under
2: Version the issue was seen in

To make sure I have covered all the cases.

**Comment by montseel** [comment] 2018-04-22 19:46
2 - I was using Valkyrie 1.6.1 on a Mac
