### ISSUE TITLE
Crawl file system for apps if the registry fails

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#656] opened 2017-11-09 02:39 UTC
In my case the key:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App ...`

was not available, because I reinstalled my Windows. The MOM app itself worked fine. A reinstall of the MOM app fixed it. So it would be nice to have a second option to find the apps.

**Comment by NPBruce** [comment] 2017-11-09 10:54
There is a -import command line flag to tell it.  I don't like the idea of searching the whole hd.  In the future perhaps a GUI interface to -import.

**Comment by NicolaZee** [comment] 2017-11-10 16:15
I don't understand why this FFG registry setting counts as a Valkyrie issue?
I'm not saying it is not.
I'm just curious about what the issue is? : )

**Comment by redwolf2** [comment] 2017-11-10 17:03
Issue as in "issue tracker" is a far fetched term devs established for "problem", "feature request", "enhancement", "bug", "support case". It should not be confused with the meaning of the ordinary word "issue" (like a problem).

Valkyrie is dependend on the FFG MOM app, that will create a registry key on install. Valkyrie will use this key as a quick way to access it. This key is not available, if the app files are copied over manually from another computer (for example). How Valkyrie handles this situation is a philosophy question. It could just don't handle it and crash, exit with a warning message, exit only with a log warning, show a filebrowser and let the user pick the FFG MOM app location as bruce suggested, crawl the whole file system, hook into Steam or use other heuristic techniques to get it done ;).

**Comment by NicolaZee** [comment] 2017-11-10 17:49
Fair enough.
_How Valkyrie handles this situation is a question of philosophy._
Agreed.

Personally I'd go for a message displayed to the user with the offending key and get them to deal with it but this might alienate less computer savvy users! : )
It all depends on how computer savvy users are expected to be when dealing with the app.
Hopefully as things progress... less and less! : )

**Comment by NPBruce** [comment] 2017-11-13 21:23
This is probably the best solution, though it doesn't work on Linux:
https://github.com/gkngkc/UnityStandaloneFileBrowser

Could also use this for package saving.

**Comment by BenRQ** [comment] 2018-10-27 23:04
I pushed my dev for this issue in branch dev_2.2.
The red button saying to install MoM/D2E is now also a button to select a directory manually.

This is only available for Windows, Mac, Linux as the file browser https://github.com/gkngkc/UnityStandaloneFileBrowser is not available for Android.

Tested on windows: it works fine for me.

I think we need to do some tests before closing this one.
I would be surprised if it worked without any surprises.

@redwolf2 do you have a Linux or Mac to test ?

**Comment by redwolf2** [comment] 2018-10-29 01:28
I fear not. We can test on a VM machine though.

**Comment by redwolf2** [comment] 2019-01-30 18:04
> In order to obtain a Steam games folder you have to follow this steps:
> 
>  1. find Steam installation folder
>  2. check Steam `acf` files and `libraryfolders.vdf`
> 
> You can find Steam `InstallPath` in windows registry:
> 
>  - 32-bit: `HKEY_LOCAL_MACHINE\SOFTWARE\Valve\Steam`
>  - 64-bit: `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam`
> 
> You can [read a Value from a Registry Key][1] using this code:
> 
>     Dim strSteamInstallPath as String = My.Computer.Registry.GetValue(
>         "HKEY_LOCAL_MACHINE\SOFTWARE\Valve\Steam", "InstallPath", Nothing)
> 
>     MsgBox("The install path is " & strSteamInstallPath)
> 
> Once you have Steam main folder (the one containing `steam.exe`) you can read games installation folder from `appmanifest_<steamappid>.acf` files contained in `\steamapps` subfolder.
> 
> For example, `appmanifest_2280.acf` contains informations about `Ultimate Doom`.
> 
> You can search for a particular `steamappid` or analyze every files and get game name from `name` key.
> 
> Also check `libraryfolders.vdf` in `\steamapps` subfolder for other game installation folders.
> 
> For example I have some games in `D:\mygames` so my `libraryfolders.vdf` is:
> 
>     "LibraryFolders"
>     {
>     	"TimeNextStatsReport"   "xxxxxxxxxxx"
>     	"ContentStatsID"        "xxxxxxxxxxx"
>     	"1"                     "D:\\mygames"
>     }
> 
> Once you have this alternative folder, check for `acm` files contained in `\steamapps` subfolder.
> 
>   [1]: https://msdn.microsoft.com/en-us/library/xz88758e.aspx

https://stackoverflow.com/questions/34090258/find-steam-games-folder/34091380#34091380

This method would be much more reliant.

**Comment by BenRQ** [comment] 2019-02-10 17:32
I've seen some feedback from people using this with success in test build of 2.2.

Closing.

**Closed by BenRQ** 2019-02-10 17:32 UTC
Labels: To be tested, enhancement, help wanted
