### ISSUE TITLE
[Android] Black Start Screen

### ISSUE THREAD

**Issue by galdernunez** [NPBruce/valkyrie#1123] opened 2019-03-22 09:25 UTC
### Description of Problem or Question

Yesterday I installed the apk on two Android devices. In the tablet (Huawei M3 Lite 10) it works and in my mobile (Moto G4) only the start screen appears with the "made with Unity" logo and it remains in black.

The mansions of madness application is installed and  Valkyrie has  storage permission.

I have not installed Valkyrie before

### Valkyrie Version
2.2.04

**Comment by BenRQ** [comment] 2019-03-22 09:29
Hi @galdernunez, can you please provide a capture of the Android version on your Moto G4 device ?
I will see if I can reproduce in an emulator.

**Comment by galdernunez** [comment] 2019-03-22 09:39
If you need more help or data, tell me

![Screenshot_20190322-103656](https://user-images.githubusercontent.com/3199126/54813783-99264580-4c8e-11e9-9274-af41942a88cc.png)

**Comment by BenRQ** [comment] 2019-03-22 09:41
OK I will, I may ask you to test with future version 2.3 which has crashlytics integrated, if I'm not able to reproduce.

**Comment by redwolf2** [comment] 2019-03-22 11:19
Consider updating to Android 8.1

https://www.xda-developers.com/moto-g4-plus-finally-android-oreo-update/

**Comment by scrubbless** [comment] 2019-03-22 21:10
I had this error when Valkyrie didn't have storage permissions, but you appear to have checked that.

**Comment by galdernunez** [comment] 2019-03-22 23:27
I have tried another mobile, same model and same version of Android and it works. This is my mobile phone problem. If you want to close the incidence. Thank you very much for your attention

**Comment by BenRQ** [comment] 2019-03-22 23:48
OK thank you for your feedback on this :)

Closing.

**Closed by BenRQ** 2019-03-22 23:48 UTC
Labels: bug
