### ISSUE TITLE
Bug - Text frame is cutting into text

### ISSUE THREAD

**Issue by slycozzolino** [NPBruce/valkyrie#632] opened 2017-10-19 16:06 UTC
Text is still legible but the frame cuts into the top and bottom a little. This is only an issue on items with longer text.
![image](https://user-images.githubusercontent.com/27984327/31781089-8800dd7c-b4c5-11e7-8b98-006a93c18c0c.png)

**Comment by NPBruce** [comment] 2017-10-19 20:06
Closing as a duplicate of #553.

It would be helpful if you could provide the text of the event and the resolution you are running in that issue report.  Changing resolution is likely to avoid the problem (I still don't know why this happens in some cases).

**Closed by NPBruce** 2017-10-19 20:06 UTC
