### ISSUE TITLE
Test variable: add OR condition

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#934] opened 2018-10-26 11:58 UTC
### Description of Problem or Question
Following request is an enhancement request for creating scenarios in Valkyrie.

For my new scenario I am thinking about one story with different board layouts (selected random at start) and a random selected correct outcome. To complicated for me to just start building in Valkyrie, so I actually started designing it first on paper before I put it in Valkyrie.... Crazy world eh ;-)? 
But while making the design I found out that programming the scenario could be less complicated if the variable test in an event have the option to add an OR condition.

Currently you can test multiple variables but they are interpreted as: "Condition1 == TRUE" AND "round == 3".. then process the actions of the event. If I want also another combination of conditions to trigger the same actions I have to create a new event with the same actions but different test conditions. This could lead to a large number of events with same actions but different conditions.

I know this could be solved with "silent" tests events all calling the same action event for more consistent behavior and less chance of programming bugs. But it would be nice if there was an option to combine this in one event (for ease of programming, testing and maintenance). 

A typical use-case could be that I only want the actions to happen in certain rounds, depending if other conditions are met:
IF ("tileXrevealed == TRUE" AND "Hint1Discovered == TRUE" AND " Round == 2" ) OR
("tileYrevealed == TRUE" AND "Hint1Discovered == TRUE" AND " Round == 4" ) OR
("tileYrevealed == TRUE" AND "Hint1Discovered == TRUE" AND " Round == 7" )
THEN
 Action: Spawn something

So yes, there is a workaround but with this option some scenarios could be written less in a complicated way.

**Comment by redwolf2** [comment] 2018-10-26 12:18
We could have to option to use [lua](https://en.wikipedia.org/wiki/Lua) to script conditions, that way me have two paths for conditions, the current system and a more advanced, complex one, that allows for even more crazy conditions.

**Comment by DelphiDie** [comment] 2018-10-27 17:30
Not to disregard your idea @redwolf2 , but I think it would be better to somehow get the "OR" checks done in the simple system, instead of creating essentially a second syntax for more complex checks.

**Comment by redwolf2** [comment] 2018-10-27 19:34
You are right.

**Comment by DelphiDie** [comment] 2018-10-27 21:01
I don't think I'm necessarily right (or that you are wrong), it's just my opinion. 

But since you are one of the programmers and have a lot more knowledge about the inner workings of Valkyrie I think you are much more qualified to form an opinion than me. So I don't want to discourage you to think of new way to improve Valkyrie.

**Comment by redwolf2** [comment] 2018-10-28 12:31
No, you are right, it is better to flesh out the simple conditions first before adding something like scripting. I sometimes tend towards looking at a bigger, golden hammer instead of focussing what is the more simple route.

**Comment by kozka** [comment] 2018-11-05 13:05
Hello
from my humble opinion and seeing the possibilities of lula, for me and I guess for many who know how to program in general.
Trying to fill all the gaps with the "simple" interface seems to me more complicated for the developers, than to adapt in some way the way of adding it to the script.
In addition and imagining the possibilities, I imagine creating standard functions, which you can call repeatedly to shorten the programming.
a greeting

**Comment by antontimmermans** [comment] 2018-11-05 19:37
Standard functions would be nice, I now make 'standard Quest Events' which are always  called but use variables to influence their behavior. 

Example:  EventQMoveOneSpace is always called and will display text "you may move one space into the revealed area" Only if the variable MoveOneSpaceAllowed is set to 1 (and it will set that variable back to 0)
```
[EventQMoveOneSpace]
buttons=1
event1=
operations=MoveOneSpaceAllowed,=,0
conditions=MoveOneSpaceAllowed,!=,0
```
  
There would be more 'programming features' interresting that could simplify placing tiles and conditionally add tokens like: 
-->add ELSE condition:  IF (condition is met) THEN execute event... ELSE do something else
or 
--> return to calling event: IF (condition is met) THEN do something;  Return to calling event.

In this example I repeat each follow-up event in case  the previous event condition is not met.
```
[EventAOfficePlaceTile]
xposition=1.925227
yposition=1.817539
buttons=1
event1=EventAOfficePlaceWall
add=TileAOffice
remove=TokenAExploreLobbyOffice
operations=MoveOneSpaceAllowed,=,1 OfficeRevealed,=,1
audio=AudioEntrance

[EventAOfficePlaceWall]
xposition=1.796671
yposition=6.033134
buttons=1
event1=EventAOfficePlaceItems EventAOfficePlaceGhosts EventQPlaceDarkness EventQMoveOneSpace
add=TokenAOfficeWall

[EventAOfficePlaceItems]
comment=Place items
buttons=1
event1=EventAOfficePlaceGhosts EventQPlaceDarkness EventQMoveOneSpace

... etc....
```
Making the OR function available would make my next scenarion easier to program. I now put each OR in a separate event wich leads to an explosion of events:
Example: Place the maid ghost depending on some conditions:

```
[EventGhostPlaceMaid]
display=false
buttons=1
event1=EventGhostPlaceMaid2A1 EventGhostPlaceMaid2A2 EventGhostPlaceMaid2A3 EventGhostPlaceMaid2A4 EventGhostPlaceMaid2A5 EventGhostPlaceMaid2B1 EventGhostPlaceMaid2B2 EventGhostPlaceMaid2B3 EventGhostPlaceMaid2B4 EventGhostPlaceMaid2B5 EventGhostPlacePastor

```
But in the end I guess for valkyrie we need to find the balance of what is still programmable with a relative simple interface to keep it accessible for non-experienced programmers

(full examples available on request but not sharing them here in order to not spoil top much of my new scenario :D)

**Comment by antontimmermans** [comment] 2018-11-07 12:50
It could be a similar interface as adding buttons. but then instead of adding buttons with possibly multiple events connected, you add OR conditions with multiple AND test conditions.
- the + on the top right of that interface part adds a test (OR condition).
- a + in front of the tested variable ads a line for an additional test (AND condition)

I tried to draw it in paint: This piece should test if ((#round >0) AND (#round) <2)) OR (#round == 6)
![image](https://user-images.githubusercontent.com/42072372/48132278-517cbf80-e293-11e8-9d55-3a9e22485b46.png)
I know: it could have been test round== 1 instead of >0 and <2 but i wanted to show the and/or behavior that I would expect.

PS.: I hope I program better then I paint :D

**Comment by kozka** [comment] 2018-11-07 19:08
another simpler way would be to add the following
(or ==)
(or>)
(or> =)
(or <=)
(or <>)
to the list of signs that already exist

if (a == 1 and b == 1 or c == 1 and d == 1)
![t1](https://user-images.githubusercontent.com/15109883/48154422-e5b54980-e2c8-11e8-97c4-9422402d09a5.png)

**Comment by redwolf2** [comment] 2018-11-07 23:06
"or ==" and "and ==" look strange to me.

![valkyrie_draft](https://user-images.githubusercontent.com/4141621/48166847-28d3e480-e2ea-11e8-8d1d-d8cb19e58b5d.png)

**Comment by kozka** [comment] 2018-11-07 23:14
it is true XDD

your idea is clearer but also something bigger.

now it comes to my mind also if a place to see in the form of a tree would be possible
all these interactions between events. Open another post.

**Comment by redwolf2** [comment] 2018-11-07 23:29
Yes, the parenthesis could be shown like a tree.

 ```
(
    round
    OR
    end
)
AND
start
```
But this would pose a problem when it gets too deep. Then will have the need to scroll horizontally.

If we someday have the need to handle such complex querys, we could always add scripting.

**Comment by kozka** [comment] 2018-11-07 23:35
if that would be fine what you say. I also think it's better to add scripts.

but I was referring to a site to see all. all the events and chains of events that you have created. and the relationships between them. and in addition to see it being able to edit it or perhaps select it. but I think this is another question / idea

**Comment by redwolf2** [comment] 2018-11-07 23:47
We already had a request on discord by zcaalock for a node based approach for events, which would be really nice, but also pose too much work to implement. Something like: https://sharpaccent.com/?c=lesson&cid=27&id=265

**Comment by redwolf2** [comment] 2018-11-07 23:53
Another simple improvement for variable conditions would be just to move it up to the trigger event, because the "test" works the same as the "trigger" and is something that triggers the event.

**Comment by redwolf2** [comment] 2018-11-08 17:07
> > Another simple improvement for variable conditions would be just to move it up to the trigger event, because the "test" works the same as the "trigger" and is something that triggers the event.

> That could have been a solution if this was chosen before any scenario was written. But this would mean that all existing scenarios have to be rewritten.  I am not a fan of doing that.
Or both condition-handling methods have to be supported: the new "conditionally trigger event" AND the old "execute event only if condition is met". Both keeping support for both would be very complicated to support and might result in messy (read buggy) scenarios.
so.. with Valkyrie being what it is now I would not vote for this.

@antontimmermans No this is just a change in the GUI and won't affect the scenario format at all. Just move up "Test" near to "Trigger".

**Comment by BenRQ** [comment] 2018-11-09 07:57
I like your proposal for presentation Redwolf.
I will probably make two '+' button: one to add a test and one to add ( )

It will ensure that we always have both parentheses and test is always valid.

**Comment by BenRQ** [comment] 2018-11-14 22:50
Reporting some progress :  

![image](https://user-images.githubusercontent.com/40794717/48517799-c9d11b00-e867-11e8-8d05-da27b22e8404.png)

Creation and manipulation of test is working.

Todo still : 
 - the test itself based on this new format ^^
 - parenthesis management
 - support of old conditions system for imported data and old questions (hopefully the same work)

**Comment by BenRQ** [comment] 2018-11-14 22:52
I have also changed the "dark blue" colour of the "event link" to Cyan, it was too dark I think.
Tell me if you think it's a bad idea.

**Comment by redwolf2** [comment] 2018-11-15 03:11
Nice work. The color change is a General gold idea. The old blue had a bad contrast. Check out https://terminal.sexy/, if you needmore colors.

**Comment by antontimmermans** [comment] 2018-11-15 07:53
Nice work indeed, I am looking forward to test it.
I agree that the new blue contrast is an improvement. And speaking of contrast, I wouldn't mind if the tile display area (not the editor panel) would be a just a tiny little brighter. Or shall I create a new request for this?

**Comment by BenRQ** [comment] 2018-11-15 07:56
A new ticket would be better, with a screen capture if possible, to be sure I understand your request.

**Comment by BenRQ** [comment] 2018-11-15 23:51
Most of the development is done, and only the parenthesis management remains.
But I have to think this part a bit.

The rest of the feature is fully functional.
If someone is ready to test, I can share a test version here.

I don't believe in perfect code at the first delivery, so you should find some bugs :P

**Comment by antontimmermans** [comment] 2018-11-16 07:44
>>>Volunteer<<<
This weekend I should have time to test it

**Comment by BenRQ** [comment] 2018-11-16 21:40
Hi @antontimmermans , you will find the version here: https://we.tl/t-MBrQHXBatK

I've shared a zip so you can keep you official version and compare the behaviour if required.

**Comment by antontimmermans** [comment] 2018-11-17 12:10
Adding variable test and moving them up/down works fine and works intuitive.
Deleting a test using the red - button works for all tests except for the first and the last one:
![cannotremovefirstandlastentry](https://user-images.githubusercontent.com/42072372/48660813-53e7d200-ea68-11e8-82b0-92ba43a78ddd.jpg)

I tried to create a test in my work in progress scenario to see if the AND/OR evaluation is perfromed correctly. After the inial UI is handled, this scenario will place a test clue token. With this test token i can select which version of the manor should be placed, and which version of the story to select.
The token will be placed but when selecting the token, the test menu didn't pop up like in Valkyrie 2.1.3 . 
Test Scenario:
[ChapelDownManorTEST.zip](https://github.com/NPBruce/valkyrie/files/2591731/ChapelDownManorTEST.zip)
 fyi, Manor 1 will work (2 is not implemented yet); The Placement of a Person (the patron) token in the Office tile includes the new test. In storyline 1 ,3 and 4 he shouldappear there depending on the round nr. For testing this you best select manor 1, story 1

**Comment by antontimmermans** [comment] 2018-11-17 12:35
Tested the Editor adding up to 51 tests. Editing works fine, the UI response becomes slower on my computer when adding a new line or when toggling AND to OR above 40 test entries

**Comment by BenRQ** [comment] 2018-11-18 13:35
I will share a new version this evening, with some of the 'parenthesis'  support.
It will still be quite technical version, so you may want to test first without parenthesis.

**Comment by BenRQ** [comment] 2018-11-19 00:35
I'm almost done with parenthesis support, but unfortunately some blocking issues remain when deleting elements in the test.
I will share a version, as soon as it can be tested.

**Comment by antontimmermans** [comment] 2018-11-19 12:46
I made a Mini Testscenario for AND/OR test
It chooses a random value (1-2) for variabes A, B and C. It displays the value of the variables (Lefft to right A, B, C) with tokens:
Value == 1 -> SearchToken
Value == 2 -> ExploreToken
Then it executes the tests and displays the test of which evalutation tested correct:
A==1 AND B==1 AND C==1
A==1 AND B==1 OR C==1
A==1 OR B==1 AND C==1
A==1 OR B==1 OR C==1

The sight token infront should allow you to randomize the values again without restarting the scenario. But I could not click this button with the test version of Valkyrie that I now have.

[ANDORTEST.zip](https://github.com/NPBruce/valkyrie/files/2595273/ANDORTEST.zip)

**Comment by antontimmermans** [comment] 2018-11-19 13:12
Small update on test scenario. It still 
[ANDORTEST.zip](https://github.com/NPBruce/valkyrie/files/2595369/ANDORTEST.zip)
works as described above. at start A,B and C are give random values.
by clicknig the tokens you should be able to set them from 1 to 2. Thjis scenario fives you better control over what you want to test. The sight token no longer randomizes but just displays the test result. 
But with the test valkyrie version i have i could not activate any token so i hope it works for you @BenRQ

**Comment by BenRQ** [comment] 2018-11-19 23:08
Hi @antontimmermans,
here is an update of the version, with all the latest fix discussed.
I've tested with your first scenario and it's working fine. If you check the logs, you can see the test results.

https://we.tl/t-a7jfvd9Bnm

Parenthesis are working, you can create them, move them, and they should work as expected in the tests you create.
Also if you try to delete some parts of the tests, you should not be able to 'break' the test, it should always have a valid syntax.
That part took me some time :)

Only way to break the test is to invert opening and closing parenthesis, but I will soon fix that too.

I have not implemented the delete option on parenthesis. 
Tell me if you think it's necessary.

![image](https://user-images.githubusercontent.com/40794717/48740569-4133ef80-ec58-11e8-85b8-2abc670cdae7.png)

**Comment by antontimmermans** [comment] 2018-11-20 09:54
Tested with latest scenario:

When all parenthesis are placed in a correct way the evaluation of ALL tests went as expected:
like: (A=1 AND B=1) OR C=1 versus A=1 AND (B=1 OR C=1)
WELL DONE!
Bored by so much perfection, time to see if i can break it :) (life of a tester is partly being sadistic)

Gramatically wrong since the parenthesis is place before the AND and not after. But program didn't break and it is evaluated as A=1 AND (B=1 OR C=1)
![moveupdownandincorrect](https://user-images.githubusercontent.com/42072372/48763436-9b12d480-ecad-11e8-976b-a24cd48378dc.jpg)

Tried reversing the parenthesis ) close first , and then open ( instead of ( ). Again, program didn't break and its is evaluated as if the parenthesis where placed correctly.

Also adding empty parenthesis ( ): before test;  after the test; both before and after; somewhere inbetween: No problemo.

Time to pull out the big gun. 
![bigguntest](https://user-images.githubusercontent.com/42072372/48764459-0198f200-ecb0-11e8-861d-e9654f571782.jpg)
Any other value setting then a,b,c = 1 (for example, 211; 121, 222) would stil display this result:
![biggunresult](https://user-images.githubusercontent.com/42072372/48764495-1b3a3980-ecb0-11e8-988a-164f78d8afcc.jpg)
In this scenario test calling secquence is (when the sight token is clicked):
EventTest
->EventTest1 (a==1, b==1, c==1)
->EventTest2 (contains the messed up test as depicted above) <- any input value combination ends up here
->EventTest3
->EventTest4
->EventTest5
->EventTestNONETRUE

I have to admit. that if programs this  B..S.. for real then I would also not care what the test result would be. the good thing was: Program still didn't break.
Overall, it looks very good, It's quite a complex feature to add and so far I coud not break it.  With this level of stability and functionality I would aready be pleased and it could be used for my level of complextiy in scenario tests.

I have added the latest version of the tesscenario including the 'bigguntest':
[ANDORTEST.zip](https://github.com/NPBruce/valkyrie/files/2599097/ANDORTEST.zip)

**Comment by BenRQ** [comment] 2018-11-21 00:16
Sounds like you enjoy torturing my version :)

> Grammatically wrong since the parenthesis is place before the AND and not after

In the first screen capture, the '(' is before the AND operator.
How did you get that ? It should not be possible to end up in this situation.

I will try to add a security to make this impossible : parenthesis ) close first , and then open (

For the other tests, I understand everything is working nicely.
Almost done!

Do you think a delete button on the '(' ')' is required ?

**Comment by antontimmermans** [comment] 2018-11-21 10:38
> Sounds like you enjoy torturing my version :)

Haha. Yes i do, and when you google my name you will probably find the 'correct me' through my job-title.

> 
> > Grammatically wrong since the parenthesis is place before the AND and not after
> 
> In the first screen capture, the '(' is before the AND operator.
> How did you get that ? It should not be possible to end up in this situation.
> 

I don't know the exact sequence I clicked but I was moving the parenthesis up and down an bit. I think somewhere in that clicking sequence I might have swapped )( too .. and back ().

> I will try to add a security to make this impossible : parenthesis ) close first , and then open (
> 

Would be nice, less chance of making a mess like the biggun test. And may even solve the '(' before the AND problem

> For the other tests, I understand everything is working nicely.
> Almost done!
> 
> Do you think a delete button on the '(' ')' is required ?

Since empty '()' is not influencing the evaluation of the test, it is not blocking if you leave the delete button out. But is doesn't look really nice and I am certain that scenarios will have empty '()' because people will click the '+ (..)' button also when not intended (reflex or not sure what it does).

I am not sure what you are struggling with to add the delete button. If it is to delete the correct ')' when you delete a '(', I don't think you have to worry about that. 

- In principle there should be as many '('-s as ')'-s. So whenever a '(' is deleted, delete just any ')'. Just delete the first or last ')' you encounter. So you only have to add a '-' button to the '('.
- Another option is to add the '-' button next to the '+ (..)' button. Selecting this will just remove any parenthesis pair '(' + ')'. I would suggest the first one pair encountered, since that is most likely the one that was put in while not needed in the first place. 

In both cases it is up to the scenario writer to move any remaining parenthesis to their correct position. 

An other angle could be to implement this in a code cleaner/beautifier:

- Add as an option to the tools menu to 'clean-up' events and discard empty '()' and optionally also solves incorrectly placed '(' before AND . It is probably easy to scan for in the events.ini file. 
- Instead of a clean-up in the tools menu it could also be done when 'save&tests' or save is done. Automatic code beautify/clean-up before save.

Anyway, an experienced Scenario writer will edit events.ini for sure and will have no issue finding and deleting them if it bothers him/her. But adding a '-' button in one of the proposed ways is a cleaner solution.

Hope this helps.

**Comment by kozka** [comment] 2018-11-21 12:39
I'm glad you're moving forward,
But it would not be easier to insert a script.
for someone who does not know how to program, it's going to cost the same, learn that, put a code.
but good that if it consecena good for you. :)

**Comment by BenRQ** [comment] 2018-11-21 20:33
@kozka I think it's probably easier to construct the test in the app : easy variable selection in the app, no syntax error, no keyword to know.
And/or/ ( ) are some basic mathematical notions that most people knows.

I think it's worth the effort, and it should help non developer to make more complex scenario.

**Comment by BenRQ** [comment] 2018-11-21 20:46
@antontimmermans here is the final version with the delete button on parenthesis.
I have also added some check, so you can't make crazy move with any components so you should not be able to break now !

Good luck trying ^^

https://we.tl/t-V2TxzuMVH6

**Comment by antontimmermans** [comment] 2018-11-21 21:44
Ok, I will have a look at it tomorrow.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: BenRQ <notifications@github.com>
Verzonden: Wednesday, November 21, 2018 9:46:51 PM
Aan: NPBruce/valkyrie
CC: antontimmermans; Mention
Onderwerp: Re: [NPBruce/valkyrie] Test variable: add OR condition (#934)


@antontimmermans<https://github.com/antontimmermans> here is the final version with the delete button on parenthesis.
I have also added some check, so you can't make crazy move with any components so you should not be able to break now !

Good luck trying ^^

https://we.tl/t-V2TxzuMVH6

**Comment by antontimmermans** [comment] 2018-11-22 19:18
Keeping the order of '('berofe')' looks fine including deleting them. delete etiher '(' or ')'" does indeed delete the pair. --> solved

The parentesis is also nicely  placed behind  AND and not infront. --> This also seems solved

Evaluation of the test tesult is also correctly interpreting the parentesis.--> No regression

So far so good... again time for another big gun but a bit smaller this time.

I started with this situation:
![parenthesisok](https://user-images.githubusercontent.com/42072372/48919203-b6d6d000-ee91-11e8-9324-0541127efab7.jpg)

Then I moved the top pair down so I could switch '(' 1 with '(' 2. I then managed to create this:
![parenthesisnok](https://user-images.githubusercontent.com/42072372/48919267-05846a00-ee92-11e8-90c0-f5f9449c6fb7.jpg)

This is evaluated incorrectly: 
![parenthesisnokresult](https://user-images.githubusercontent.com/42072372/48919343-86dbfc80-ee92-11e8-87fa-75b9365cf3f8.jpg)

I then managed to delete the top ')' which did not delete '(':
![parenthesisnoktopdeleted](https://user-images.githubusercontent.com/42072372/48919451-27322100-ee93-11e8-9b4a-3d5601391f90.jpg)

the deletion of the final pair '()' worked as expected, leaving this end result:
![parenthesisnokdeletefail](https://user-images.githubusercontent.com/42072372/48919489-5f396400-ee93-11e8-9aa0-b29bd1e37159.jpg)

**Comment by BenRQ** [comment] 2018-11-22 21:36
Thanks @antontimmermans 
It's now fixed :)
I will probably make a test version for #950 later, if you want to give it a final test

I've updated "quest format" version number.

@redwolf2 @scrubbless @DelphiDie FYI, this change is a breaking change for older version of the app.
It means version 2.1.x won't be able to load scenario generated by version >= 2.2
2.2 can still read older scenario though.

With current and previous version of Valkyrie, scenarios with unsupported quest format are just not listed in download section.

Difficult to say if people have been updating a lot their 2.0 version.
Anyway it's another topic, I'm closing this issue as the work is DONE !

**Closed by BenRQ** 2018-11-22 21:36 UTC
Labels: D2E, MoM2E, enhancement

**Comment by redwolf2** [comment] 2018-11-22 21:41
In that case we have to increment the quest format version and document it here: https://github.com/NPBruce/valkyrie/wiki/QuestFormat

**Comment by BenRQ** [comment] 2018-11-22 21:45
I've incremented quest format in the latest commit : https://github.com/NPBruce/valkyrie/commit/366ad49b7062679b0ef71ae742a0b5495ed7d800

But it's strange, it has now reached 10 but the documentation state it should already be 10.

**Comment by BenRQ** [comment] 2018-11-22 21:48
Documentation is updated.
I've fixed the documentation so the latest improvements of 2.0 version are listed in format "9"

**Comment by antontimmermans** [comment] 2018-11-24 18:43
It looks as if the tests in OLD scenarios disappear and have to re-programmed

**Comment by antontimmermans** [comment] 2018-11-24 18:54
I used the latest test version that I got from @BenRQ and ALL tests in event.ini disappeared :(

**Comment by BenRQ** [comment] 2018-11-24 20:18
'Conditions' is now called 'eventtests'

The old conditions should automatically be translated in the new format.

Do you confirm tests are still working?

**Comment by antontimmermans** [comment] 2018-11-25 00:07
Not sure what happened. I might have loaded the new scenario in Valkyrie 2.1.3.  and later again in the alst test version that i received from you. ALL varialble tests, including the ones i created in the test version where gone.
including this one: (had to make 2 screenshots to capture it in total.
![patronofficetest1](https://user-images.githubusercontent.com/42072372/48974087-4628e280-f04e-11e8-9d73-7169cf5359a4.jpg)
![patronofficetest2](https://user-images.githubusercontent.com/42072372/48974088-4923d300-f04e-11e8-83e9-e88f1dec7990.jpg)
 
I am not sure but i think it might have gone wrong due to mixing old an new versions. I will stick to the test version now to avaoid this loss again.

**Comment by BenRQ** [comment] 2018-11-25 20:42
I have just tested in my latest dev version, and it is working fine.

If you want a reference version, please use the one attached here, and delete the older tests versions.
https://we.tl/t-gp9trTNOaU

**Comment by antontimmermans** [comment] 2018-12-08 13:32
@BenRQ I am still using your lastest test version to further develop my scenario using the OR test: 2.2.2018 1125_technical. So far in the evluation of the OR condition it seems to work very well. I have not found an bug in that part (yet).

1.  In the editor  it still can go wrong:
If you delete a ')' it does not always delete a '('. If you then try to delete all '('and ')' there will be a solitary '(' left. It is impossible to delete this last ')' using the red '-' button.  I have to edit the events.ini file to correct it again.
I think you can best solve this by allowing only a delete on the '('. So the ')' do not have a red '-' button. And if you delete a '(' also delete always the first next ')' that you encounter. The behavior is then predictable and the scenario writer will have to move the remaining '( )' to the correct position anyway.

2. The latest official release 2.1.5 doesn't support this OR test function (and will delete all tests in scenario's that use the OR test). So I am a bit stuck with having to keep using this technical version. When do you think the OR function can be releases in an official release?

**Comment by BenRQ** [comment] 2018-12-08 19:19
Hi @antontimmermans, this feature is part of release 2.2.
Main reason for not integrating it in release 2.1.5, is that I don't want to risk any regression on a hotfix version like version 2.1.5.

If you check the current status of the release 2.2, we have done half of it more or less.
So it's not coming before January or February I think (and I may be optimistic).
We have two big topics in this release:
 - the new scenario explorer #962 (divided in many other issues) => I'm working on this
 - the new var system  #271 => @redwolf2 is working on this

On top of that we have all the other smaller issues.

Scope of the release is open to discussion and we can scope out some of the smaller items, but I really would like to have the scenario explorer as this is I think a must have today.

So the question is : do you plan to release you scenario before that date ?

And thanks for the bug report, I will check it :)

**Comment by BenRQ** [comment] 2018-12-10 00:10
2.1.5 uses the old syntax still.

New syntax will be introduced with version 2.2

**Comment by antontimmermans** [comment] 2018-12-17 09:06
@BenRQ ,

FYI: this weekend I managed to complete the complex ghost placement part of my new scenario. The (sometimes complex) conditional placement events alone add up to ~80 events. Without the OR and the test-parenthesis I estimate that this would have been 4 times more. 
I also ran the first 'big' test to check the placement behavior and found that some placements where incorrect. These placement errors could all be traced back to my own incorrect use of AND instead of OR (or vice versa).
Which means: after this weekend with I am quite confident that this new feature works also correct in more extensive tests and is also very robust (doesn't break). 

**Congratulations on this job well done.**

**Comment by antontimmermans** [comment] 2019-01-05 13:07
Hi @BenRQ 

I am affraid I bumped into a bug in the editor handling the AND/OR:
![image](https://user-images.githubusercontent.com/42072372/50724750-a3ef2680-10f2-11e9-93ca-1cd3ce7039e2.png)

I started to add testsvariables and they where simply placed on top of eachother (no AND/OR between them) Adding parenthesis didn't change it nor did moving anything up and down.

Valkyrie2.2.20181209 test version

**Comment by BenRQ** [comment] 2019-01-06 11:37
Hi @antontimmermans 
would you be able to reproduce the problem easily ? Any idea what could have caused it ?

It would be great if you could switch to a more recent test version too.
(I hope) I will soon create a new test version with the new scenario loading mechanism.
I will then give you some instructions on how to make your scenario compatible with the new test version.

**Comment by antontimmermans** [comment] 2019-01-07 10:59
Hi @BenRQ 
I am afraid is was very much focused on making big steps in my new scenario so I quickly solved this problem by editing the .ini file.
If I remember correctly, it started by just adding  3 test variables which where stacked directly on top of each other (No AND/OR was added in between). I can't remember what I did to get some AND/OR  between the variables, I think that happened when I added  brackets. One AND/OR was added but not others. Moving the brackets also did not add more conditions.
When ever you are ready to share a new test version I will try to recreate this situation and pay more attention to what I am clicking.

**Comment by antontimmermans** [comment] 2019-02-23 13:42
@BenRQ i noticed unexpected behavior in making a new test: No  AND is added inbetween test variables.
![image](https://user-images.githubusercontent.com/42072372/53287193-cdcedc00-3778-11e9-8371-ec007c8a1eb0.png)
I think this happens when you add a second test variable which is NEW (not selected from the list)
if you add a vaiable that already exists.. it DOES add an AND
![image](https://user-images.githubusercontent.com/42072372/53287210-256d4780-3779-11e9-8da6-0fae69341ab1.png)

**Comment by redwolf2** [comment] 2019-02-23 23:40
@antontimmermans Your issue was fixed and moved by @BenRQ to this issue: https://github.com/NPBruce/valkyrie/issues/1091
