### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#412] opened 2017-05-09 13:09 UTC
Is there already a way to stop the background music for a short time?
Im asking that because i did record some music for myself that i want to use in key moments of the scenario and its a bit disturbing if the "usual" background music is still playing at the same time...

**Comment by redwolf2** [comment] 2017-05-09 15:44
IMO these are possible sound events:
- Replace looping background music
- Play a one time music track, that mutes or fades in and out of the background music, while it is playing (like a drama music track, when a shoggi activated).
- Play a sound effect while the background music is playing (like a creaking door).
- Play voice track and mute the background music, while it is playing.

All those requirements could just be parameterized by the sound event.

**Comment by NPBruce** [comment] 2017-05-09 21:39
Closing as duplicate of #165, splitting animation idea to #413

**Closed** 2017-05-09 21:39 UTC
