### ISSUE TITLE
Translations into Portuguese

### ISSUE THREAD

**Issue by danielfrancelino** [NPBruce/valkyrie#870] opened 2018-07-29 12:40 UTC
### Hello, I've just installed the latest valkirie for windows and noticed that just one scenario is available in Portuguese. So I'd like to translate the scenarios into Portuguese. Could you walk me through how should I proceed to create the translation? I'm not a developer, I'm actually a technical writer, but I know a lot of people in Brazil would use valkirie if we had more scenarios translated.
So, where could I find the text files in English? Can I edit them in a simple text editor, just translating into Portuguese? I appreciate a lot if you could guide me for my first translation.

**Comment by scrubbless** [comment] 2018-07-29 19:45
Hi @danielfrancelino, 

@nzocrato is working on a Portuguese translation of "Stress and Strain" and may have some tips for you.

I have added a section to my Valkyrie guide regarding translating scenarios (Page 130 onwards):
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/

**Comment by nzocrato** [comment] 2018-07-29 22:15
Hi @danielfrancelino, 
This is great i have started working to translate the scenarios for the same reason, i think once we have them published on portuguese the brazilian community will embrace valkyrie.

As @scrubbless have said im working on Stress and Strain, i think you will realize its pretty simple to translate following the guide, any questions u have just PM me and i'll be glad to help. 

Im doing the job working inside valkyrie to try to not corrupt any files, its not going fast and i don't have much time actually but i think it will be great, actually ill tell you its kind of a bitter sweet situation because i really want to play the scenario and doing the translation u kinda of know everything that can happen in the scenario so when i get to play it with my friends it will not be the same experience to me. 

So im glad you will join me in the "Brazilian team" to translate all scenarios, this way ill get to play some of them without spoilers =)  

Its really important to leave thread here and notify de creator and other so we don't work on the same scenarios at the same time. 

You can get a notion of how the currently scenarios are rated here:
https://boardgamegeek.com/thread/1916430/fan-made-scenarios-reviews-valkyrie/page/1

You will see that i choose stress and strain because it had great reviews, so i suggest you pick In the dark?
It appears to be another great scenario.

That's it, take a look at the guide @scrubbless  have provided, and any questions im here.

Thanks

**Comment by scrubbless** [comment] 2018-07-29 22:29
In the Dark would be a great choice, also the creator @NicolaZee is always very responsive and helpful if you reach out to her.

@nzocrato  you seem to be fluent in English, you could always play the scenario 2 player on your own in before translating. Least then you will get a spoiler free view of the scenario. Also it might help you understand the narrative of the scenario.

I am translating Razon (10:30h at the Bird Shop), however I do not speak any spanish so I am translating that with Google Translate and tidying up the dialogue. So I won't get to play that spoiler free for sure :(.
I am using the editor too, this way I can read the events in sequence so I understand the narrative and the events leading up to any "badly google translated" dialogues, I can at least understand what lead to them, so I can try to work it out!

**Comment by danielfrancelino** [comment] 2018-07-30 11:04
It's a deal then! I'll start with In the Dark. As @scrubbless said, before I'll try this scenario in English, so I can have a better feeling before starting to translate.
@NicolaZee is it ok if I translate this scenario into Portuguese?

**Comment by NicolaZee** [comment] 2018-07-30 12:58
Be my guest.
It's a very good idea to try it in English first as I will admit 'In the Dark' is not so forgiving or accessible as 'Stress and Strain'.  It really is a 5 star difficulty.  As James put it it's a mind-melter!

The good news is even after playing it many many times I still find difficulty working out the mystery!
As you will discover there is a lot going on beneath the surface.

**Comment by BenRQ** [comment] 2018-07-30 18:15
Hi all,
here is my personal method for translation, as I realize it is quite different.
Maybe it can benefit some of you.

I agree it's important to try the scenario first, and understand the flow of events.

But I find it quite hard to do the translations from the editor, or from a text file.
First of all, I think it takes a lot of time to rewrite all text, and to try to find the right translation, when you are not native speaker of the original text. So I use automatic translation, and I fix/improve 50% of the words.
(please note automatic translation quality is very dependant on the languages, and it is quite good for French, this may not apply to all languages).

With text files, you can't put comments, remarks, text color, mark questions while you are doing it.
Also you don't have saves / automatic versioning, if you do something wrong ^^
That's why I use an online editor like google sheet, with one cell per event text.

What I do: 
1) I extract the text file into a excel / google sheet
2) I separate event name and text in two columns (this is a bit technical as you have a use regexp, but can be done very fast once you know how to do it)
3) translate all line via google translate or any other tool
4) put the translation in a third column, so it is easy to read both column at the same time
5) then I adapt / rewrite every line so it fits the meaning, and original writing style
6) finally, I make sure to keep the technical tag between { } intact, this may have been touched by the automatic translation.

Once it is done, extraction to a txt file is just a copy paste to a text editor, and a replace, to remove the 'tabs' between event and text.

I'm happy to help someone to show how I create the spreadsheet (it takes me 2 minutes to do), so feel free to ask.

**Comment by nzocrato** [comment] 2018-07-30 18:28
@BenRQ This sounds great, and apparently its faster than the inside translation. Can u give a walkthrough on how to separate the event name and text and create the spreadsheet?

Thanks!

**Comment by danielfrancelino** [comment] 2018-07-30 18:29
Hi @BenRQ !
That seems to be a very efficient process. Would you mind helping me to create the spreadsheet to In the Dark scenario?
Google has improved the Portuguese translation a lot. Although it still does to be 100% verified, it's much easier than rewriting everything.

**Comment by nzocrato** [comment] 2018-07-30 18:38
@BenRQ @danielfrancelino @scrubbless @NPBruce 

 I just thought that if this way really works and proves to be faster. We could great one google sheet for each scenario this way, and leave it open for translation into any language. Each column one different language, that would accelerate the process even more since we would be even able to work together in the same scenario, and of course look to how the sentence had been translate to other languages in the same spreadsheet.

Every new scenario we would just create the new spreadsheet and leave it open to translation into any language.

What do u guys think?

**Comment by danielfrancelino** [comment] 2018-07-30 18:45
@NPBruce seems great!!
And also would be easy to make corrections in future, in case somebody finds an issue in the translations (happens very often in my area of work).

**Comment by BenRQ** [comment] 2018-07-30 18:49
Sure let me prepare a step by step, while I'm doing it on the in the Dark scenario.

**Comment by BenRQ** [comment] 2018-07-30 18:54
@scrubbless you tutorial is really great.

The wiki is good, but this document would be a great addition to the existing documentation.
Is it available in the Wiki ?

It could even be listed in the main page of the GitHub as I guess a lot of person are looking for this kind of 'step by step' doc.

**Comment by BenRQ** [comment] 2018-07-30 19:39
**To create the spreadsheet:**
1) Open the txt file in a txt editor, like Notepad++
2) replace the ',' between event name and text, by a character that is not used anywhere else : I used 'tab' (as it is recognized by most tools to separate column in step 4).
Here is the regexp: ^([a-zA-Z0-9]*\.*[a-zA-Z0-9]*)\,
![image](https://user-images.githubusercontent.com/40794717/43418013-f43cdaac-943c-11e8-8d88-a97313e18b3a.png)
3) paste results in a google sheet / excel
4) use the function to separate text into column ( this is automatic with tabs in google sheet)

**To translate:**
1) Copy/paste column B in a text file
2) Use the text import option of google translate, and import this file
![image](https://user-images.githubusercontent.com/40794717/43418355-ee472214-943d-11e8-9533-1a82e0edbbc2.png)
3) copy paste results in the spreadsheet in column C
-- Please note I had to step 2 and 3 a few times as google translate seems to have a maximum number of lines with Portuguese... Don't think it is the case with French
4) fix special technical tags with a few 'replace'
</ i> -> </i>
\ n -> \n
{pista} -> {clue}
{c:[space]  -> {c:
{qst:[space]  -> {qst:
{[space]  -> {

**Et voilà**

File is available, I would need an email to share it with you (you can delete the post after).

**Comment by danielfrancelino** [comment] 2018-07-30 19:50
Awesome! Mine is Danielfrance@gmail.com

**Comment by scrubbless** [comment] 2018-07-30 19:57
I'll give this a shot for Razon, looks  much easier.

**Comment by scrubbless** [comment] 2018-07-30 19:58
I'm just putting the final bug fixes in for "Strain of Reality" my next scenario. But it's mammoth task, 70,000 words in the localisation file at last count!

**Comment by BenRQ** [comment] 2018-07-30 20:29
I'm glad I could help :)

@nzocrato, @scrubbless  tell me if you need help to create the doc.

@danielfrancelino, file is shared now, you can also share it yourself if you wish.

**Comment by danielfrancelino** [comment] 2018-07-30 20:58
Thanks a lot @benrq. Certainly made our job a lot easier.

**Comment by NPBruce** [comment] 2018-07-30 22:55
When saved with the current version of Valkyrie the language files should be csv compliant (in so far as that is a thing). Can you try just renaming to .csv and open directly?

Would it be better to change the default extension?

**Comment by danielfrancelino** [comment] 2018-07-31 00:26
This is where I have to tell you I'm feeling a little stupid. I don't have all expansions and I didn't realize that I needed the Suppressed Memories expansion for playing In the Dark. At this point, the only real problem is keeping consistency with the already translated tiles, cards and monsters for this expansion.
@nzocrato do you happen to have Memórias Reprimidas expansion? If so, is it too much to ask if you could take pictures of the contents? cards, monsters, etc. so I could check the Portuguese names already adopted by Galapagos? Pictures just good enough so I could read the names.
If I just translate the names, we are in risk of making incorrect references in the text.
Otherwize, I may just try translating another scenario.

**Comment by nzocrato** [comment] 2018-07-31 00:33
@danielfrancelino Hi Daniel. Guys im gonna answer this one in portuguese.

Oi Daniel, então esses elementos Cartas, peças de tabuleiro, monstros e tudo mais você não precisa traduzir, justamente para não causar esse tipo de falta de consistencia. O valkyrie extrai esses nomes da tradução original da Galapagos, quando ele extrai os dados do app oficial.

Quando você ta montando um mapa no valkyrie você referencia as coisas por exemplo {clue} esses elementos que você vai ver no texto eles se auto traduzem, {clue} no caso quando rodar o texto no valkyrie só de já estar marcado a lingua como portugues vai aparecer "pista". Assim como os nomes das cartas, monstros, etc. Esses elementos então você tem que deixar sem traduzir na forma do código que eles se apresentam.

Acho que deu pra entender?

**Comment by danielfrancelino** [comment] 2018-07-31 00:47
@nzocrato deixa eu ver se consegui compreender. No arquivo em excel, por exemplo, temos uma entrada em inglês como a seguir, sem as aspas:
"{action} <i>Is Eric Colt a Dark Druid?</i>"
O nome do monstro seria Dark Druid, em inglês. Mas na entrada em inglês, não está entre chaves {}. Você diz então que, se eu colocar entre aspas, ele vai procurar por uma tradução deste monstro? Desta forma a seguir?
"{action} <i> Eric Colt é um {Dark Druid}? </i>"

**Comment by nzocrato** [comment] 2018-07-31 00:52
Nesse caso acredito que não está referenciando um monstro e não irá procurar pela tradução, pois é apenas um campo de texto. Dark Druid, o app não está chamando o monstro, ou movendo o monstro, eventos com o monstro. 

Nesse seu caso se o texto do cenário está se referindo a monstros sem referenciar então realmente seria um problema.

Vou dar uma olhada aqui, me da share no arquivo
nzocrato@gmail.com

**Comment by danielfrancelino** [comment] 2018-07-31 00:56
Compartilhei! Os textos tachados são aqueles que já conferi!

**Comment by nzocrato** [comment] 2018-07-31 01:05
Sim, estou vendo aqui:

O caso que eu me referia era tipo neste caso : " If you have the {c:QItemCultSigil} Item you may use an {action} to get it out and hold it up to the door grille "

Perceba que a referencia {c:QItemCultSigil} já vai traduzir automaticamente o nome do item, pq ta chamando ele da base de dados. Agora nestes outros casos você realmente tem que traduzir o nome.

Não sendo uma referencia direta a algum componente do jogo. Nestes casos acho que você adotando uma coerência interna sua na tradução não haverá problema. Dark druid = Druida Negro
Este é um problema que estou vendo em mandar tudo no google translate, se ele alterar essas referencias internas pode complicar

**Comment by BenRQ** [comment] 2018-07-31 06:52
> When saved with the current version of Valkyrie the language files should be csv compliant (in so far as that is a thing). Can you try just renaming to .csv and open directly?
> Would it be better to change the default extension?

@NPBruce as commas and semicolon are used in the text itself, it would create many columns instead of two, and modify the text by removing those characters, if you would open it in directly a spreadsheet editor like Google sheet or excel.

If you would replace the first comma by a 'tabulation' in the editor and it every translation, it may work though.

**Comment by nzocrato** [comment] 2018-08-01 11:55
@danielfrancelino Hi, did u find a solution for that problem?

**Comment by danielfrancelino** [comment] 2018-08-01 12:03
@nzocrato Hello, you are still referring to the consistency in terminology? I'm translating the names that are not in a {} and keeping them the same throughout the various dialogues, but I still would like to use the same translation as Galapagos. I asked in a MoM group if somebody has a list or photos of their expansions. Worst case scenario is that, after published, people will complain about terms I've used are different when compared with Galapagos cards and tokens.

**Comment by nzocrato** [comment] 2018-08-01 12:13
@danielfrancelino hmm, i have a idea. Find a way to highlight all these itens and monsters that you have doubt about the Galapagos translation, when you're done, ill look into my copy of Memorias Reprimidas and check if your translation matches theirs. If not ill just do a find and replace in the entire text to match the galapagos.

**Comment by nzocrato** [comment] 2018-08-01 18:41
Yeah, no problem, we can do it that way. Just call me when its done ! Looking forward to play In the Dark ( No escuro? )

**Comment by BenRQ** [comment] 2018-08-01 18:50
Hi,
if you are looking for the official game translations of objects, tiles, spells ... and so on, they are available in a text file in the official app.
Valkyrie imports it.

File is here  :  
C:\Users\[your_username]\AppData\Roaming\Valkyrie\MoM\import\text

[Localization_pt.txt](https://github.com/NPBruce/valkyrie/files/2250739/Localization_pt.txt)

**Comment by BenRQ** [comment] 2018-08-01 19:32
I did not install the expansion on the official app, as I don't have it.

Maybe you need to install the extension on your computer in the official app, and import content again?

**Comment by andrex47** [comment] 2018-08-02 18:36
It is really great to see people putting effort in those translations, right now i'm translating "Believe Or Die - The Search For Ashcan Pete"

**Comment by scrubbless** [comment] 2018-08-02 18:45
Hi guys,

On the topic of tile names, instead of translating the tile name, you could simply replace it with the component name.

For example 
The hall 2 tile is placed in an event and the dialogue says:
"Hall 2 {MAD20}"

Then in the "add components" section a tile is added with the component name "Tile1".

In the dialogue you can replace that with the tile components name, {c:Tile1}. That will persist through all languages as the variable has different languages.

You will notice this in Stress and Strain. The reason I did this was if I decided to change the tile, QItem, etc. I wouldn't have to go and change it in the events. 

I have not tried, but I suspect you can do the same with spawns.

**Comment by nzocrato** [comment] 2018-08-02 18:54
Hi Scrubbles, 

Yeah, our discussion its based on that, i noticed you did that, and thought every scenario would be that way, so i just said to daniel that he didn't had to translate those parts, but then we found out that if the creator of the scenario didn't put it that way its a extra work to translate.

Its a good practice to do it all just using references i guess u should add that in your guide !

Thanks

**Comment by scrubbless** [comment] 2018-08-02 19:10
I did! :D 
![screenshot_20180802-200816_docs](https://user-images.githubusercontent.com/32058089/43605365-00e90ad2-9690-11e8-8ded-00d3d372011e.jpg)

**Comment by NicolaZee** [comment] 2018-08-03 07:05
There seems to be some confusion about what is being discussed in regards to names.
With 'In the Dark' the **tile** names do use the {c:TileName} reference.

The issue is with the monster names - in particular the name  'Dark Druid'.
In hindsight it might have been better to use the monster reference name.
With the 'Dark Young' monster, I should have used the monster reference.

But with the term 'Dark Druid' it gets more complicated because there are times I have to refer to **a** Dark Druid rather than **the** Dark Druid.   James knows the terminology used to refer to the Druids can get confusing.  It could be argued there are places where the term an **evil** Druid might be more appropriate and helpful.  e.g.  "{action} Is Eric Colt an evil Druid?" rather than  "{action} Is Eric Colt a Dark Druid?" 

But I decided not to go down that route because part of the challenge of 'In the Dark' is figuring things out.  Each clue subtly reveals information.  The investigators should soon learn that they are trying to discover who is 'The Dark Druid' but as the investigations progresses they discover....

Spoiler Follows....

There is The Dark Druid and the Dark Druid's acolyte.  Both are evil Druids.  Only one is The Dark Druid.

I hope this helps.

**Comment by scrubbless** [comment] 2018-08-03 08:43
They are all new techniques to me Nicola! If you work it out, let me know and i'll add it to the guide.

**Comment by NicolaZee** [comment] 2018-08-03 08:56
Hello James

I'm going to add a new Valkyrie issue as I can't figure out how to access EXPLORE_MOVE.

**Comment by nzocrato** [comment] 2018-08-03 12:20
Hi @NicolaZee, i thought that ! Since In the dark is so subtle i think it will be a huge challenge to translate it keeping every clue in the way they were in the original version. Well its up to @danielfrancelino now!

**Comment by NicolaZee** [comment] 2018-08-03 12:48
Without a doubt, 'In the Dark' is the hardest scenario to translate.
This is not because there is huge amounts of text.
The text file is smaller in size than 'Stress and Strain'.
Th problem is that it resembles a little bit a 'Sherlock Holmes Consulting Detective' scenario because every clue contains a clue and in some cases multiple clues.
It might help if I typed up the background underlying story because it might help to put into context the clues.

**Comment by danielfrancelino** [comment] 2018-08-03 12:57
It'll take some time, but I'm really excited to put the translated version into test. I hope the translation does not become a challenge for the players, rather than the scenario itself.

**Comment by danielfrancelino** [comment] 2018-08-06 12:41
In the dark translation is 50% done!

**Comment by danielfrancelino** [comment] 2018-08-06 14:17
@nzocrato , can you gimme a hand? Could you check in your collection if you have the "Dark Druid Monster"? If you do, can you check the name in Portuguese?

**Comment by NicolaZee** [comment] 2018-08-06 14:52
In the localisation text file Localization_pt.txt  the translation of Dark Druid is:
MONSTER_DARK_DRUID,Druida Sombrio
So, I think FFG uses the term Druida Sombrio
FFG's translation seems to me to be more Spanish but more than likely I'm confused.
I tried Google automatic translation and the term Dark Druid translates as Druida Escuro.
To maintain consistency with the rest of the text used by FFG maybe you'll have to go with matching whatever FFG uses?

Maybe Bruce can help clarify whether the Localization_pt.txt  is the correct text file for Portuguese.

**Comment by nzocrato** [comment] 2018-08-06 15:24
![p_20180806_122030](https://user-images.githubusercontent.com/10546003/43725683-906c6a38-9973-11e8-8a6f-9d6ffc82a813.jpg)

@danielfrancelino I took a picture of The monsters reference guide.

**Comment by NicolaZee** [comment] 2018-08-06 16:04
Excellent Idea.
So Druida Sombrio it is then!

:)

**Comment by danielfrancelino** [comment] 2018-08-08 21:53
@nzocrato I have only the MoM 2nd edition and I didn't even had curiosity of opening the conversion kit for 1st edition that actually comes with the 2nd edition. I opened it today and guess what? It comes with the monster tiles whose translated names I was looking for...

**Comment by danielfrancelino** [comment] 2018-08-08 23:43
@nzocrato would you mind helping me again with a translation? Did  you happen to find the Portuguese translation for the Thrall monster? 
![image](https://user-images.githubusercontent.com/41863856/43869853-19ef35aa-9b4b-11e8-8a2a-7b1b118486f2.png)
That's the last term I need to finish the translation of the In the Dark scenario.

@BenRQ , could you help us again with converting the excel file into the txt localization file?

**Comment by nzocrato** [comment] 2018-08-08 23:47
@danielfrancelino  Thrall = Thrall

=)

**Comment by danielfrancelino** [comment] 2018-08-09 00:08
So I guess I'm done!

**Comment by BenRQ** [comment] 2018-08-09 07:01
Hi @danielfrancelino,

I did the first one but you will probably need to do it again if you play-test it with some friends.
Here is how you can do it
 1) you copy/ paste the column A and B into a text editor
 2)  replace all TAB with ','  (you should copy paste the tab character from the text, between event id and translation)
 3) save file with the right name translation.portugese.txt
It's done.

You can compare with this file if you want to be sure you did it right.

[translation.portugese.txt](https://github.com/NPBruce/valkyrie/files/2273085/translation.portugese.txt)

**Comment by danielfrancelino** [comment] 2018-08-09 11:13
@NicolaZee I've finished translating In the Dark into Portuguese. 
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2273928/Localization.Portuguese.txt)

What would be the next step? I'd like to run this scenario in Valkyrie to validate the translation (find possible mistakes). What would you recommend?

**Comment by NicolaZee** [comment] 2018-08-09 13:51
Locate your app data editor folder
%AppData%\Roaming\Valkyrie

Open Quest.Ini using a text editor.
Add the line Localization.Portuguese.txt to the [QuestText] section of the file.

[QuestText]
Localization.English.txt
Localization.French.txt
Localization.Portuguese.txt

Run Valkyrie
Click the 'Options' button in Valkyrie and set your language to .Portuguese.

Good Luck and please don't hesitate to ask any question.

**Comment by NicolaZee** [comment] 2018-08-09 14:05
Hello danielfrancelino

Have you printed out the crib sheet that goes with the scenario.
If not, I strongly recommend you do so.

I'd, also, recommend making notes as well.

There is only so much information most people can cope with!

**Comment by scrubbless** [comment] 2018-08-09 15:06
May be worth translating that document too if its got a lot of text on it.

**Comment by danielfrancelino** [comment] 2018-08-09 17:15
Hi @NicolaZee , I located the folder %AppData%\Roaming\Valkyrie\Mom\Editor\InTheDark
But it seems empty. Are the files hidden or something?

**Comment by danielfrancelino** [comment] 2018-08-09 18:05
@NicolaZee and @scrubbless , here it goes the crib sheet translated into Portuguese as well:
[InTheDarkClueCribSheet-Portuguese.pdf](https://github.com/NPBruce/valkyrie/files/2275337/InTheDarkClueCribSheet-Portuguese.pdf)

**Comment by danielfrancelino** [comment] 2018-08-22 17:17
Hi @NicolaZee ! Following your instructions, I did a few playtests and corrected all issues I found. I also renamed the scenario to v3.5.
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2311354/Localization.Portuguese.txt)
Do you believe we need more testing? From my side, we are good with the translated version above. What do you think?

**Comment by NicolaZee** [comment] 2018-08-23 05:47
Hello danielfrancelino

Language can be very ambiguous.
It is very easy to get a few words here and there a bit wrong and the mystery becomes incoherent.
The translation to French took Indoy hours of work and testing was very hard.
Much harder than the other scenarios he worked on.

So my main question is did the scenario make sense?
Did the printed out pdf sheet make sense?
Did you manage to win?
Most people take around 3 attempts before they win!
Last but not least what did you think of the scenario.
Most people think it's good but much too hard!

**Comment by NicolaZee** [comment] 2018-08-23 11:11
Hello danielfrancelino

Have you tried it with more than 3 investigators?
If you play with more than 3, there is a 2 in 3 chance of a plot twist.

**Comment by danielfrancelino** [comment] 2018-08-23 11:45
Well, for me it took a lot of time indeed. And the playtest made me change many sentences I already translated, so they would make more sense. Besides all wrong tags, extra spaces, missing spaces and so on.
I won exactly on my third attempt. And only managed to win after using the pdf for notes. After that I had a few defeats, this time on purpose, aiming to check other dialogues.

**Comment by danielfrancelino** [comment] 2018-08-23 11:56
But I always used only 2 investigators. So I didn't see the plot twist.
I think it's a great scenario. Of course it's hard. It's mansions of madness. ;)
I'd say it's my preferred type of scenario. Investigation rather than pure fighting monsters.
I love eldritch horror, for example, but if you don't do the role-playing, it' just tossing dice and praying for the next mythos card don't execute everybody in a glimpse.
In the dark makes you actively responsible for the direction of the story. You can be all successes in your dice, and yet fail miserably dues to poor judgement (like my couple of playtests).

**Comment by NicolaZee** [comment] 2018-08-23 12:56
I'm very glad you enjoyed my scenario.
That's a relief as otherwise it would have been a waste of the time you spent translating it.
With 5 star scenarios, you get out what you put in.
In addition (because of the complexity and variation) if you don't play it for a few months (especially with 4 investigators) you'd be surprised how much of a challenge the scenario can still be.
I call it 'the Beast' and it has claws!
If you ever start finding it too easy, just play it with no crib sheet!
Then for the ultimate challenge, play it with no notes.
I don't recommend this because I've never won 'In the Dark' playing with no notes.

In  a sense playing with the 2 investigators is a slightly cut-down version because the plot-twist is turned off.
With less than 4, there is no chance of a plot twist.
With 4, there is only a 2 in 3 chance of a plot twist.
I'd recommend playing once with 4 but without laying tiles, monsters and so on and cheating on the dice rolls so you just treat them as automatic successes.

Alternatively (if you're confident of your translation) I'm happy to release it as is with the attribution:
Portugese Translastion: DanielFrancelino

**Comment by danielfrancelino** [comment] 2018-08-23 17:11
You got me curious. I'll try it first with four investigators :)

**Comment by danielfrancelino** [comment] 2018-08-24 16:04
@NicolaZee I guess I'm pretty confindent with the translation! Did a couple more of playtests today.
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2319056/Localization.Portuguese.txt)
If you don't mind releasing it, I guess my job with with scenario is done. It's a pitty that translating it and playing that many times kind of spoil the fun. However, I'm gone try it again in a few months. Such a great scenario!
@nzocrato you are working with stress and strain, correct? I'm looking for my next translation challenge.
I remember that somebody is translating Believe Or Die - A Search For Ashcan Pete.
A glimpse of the past is already translated.
So Amnesia, In Places Unseen, and Exotic Material are possible candidates, right?
@NPBruce , what is your suggestion?

By the way, thanks everyone for the kind support!!

**Comment by NicolaZee** [comment] 2018-08-25 07:14
Hello danielfrancelino

Thanks for your praise.
Great work on the translation - especially on the play-testing
Any feedback is gratefully received.
Please don't forget to vote on the poll in BGG! 

I am very happy to release your translation.
Playing many times does spoil the fun.
You are likely to find the next scenario you do is a lot less work!

**Comment by NicolaZee** [comment] 2018-08-27 10:02
Hello danielfrancelino

Portuguese Translation now released as version 3.5

**Closed** 2018-10-04 23:09 UTC
Labels: Scenario
