### ISSUE TITLE
Dialog box clipping

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#674] opened 2017-11-17 17:12 UTC
I quite frequently find that the dialog boxes clip through some text:
![image](https://user-images.githubusercontent.com/32058089/32959674-40e7c3a4-cbba-11e7-8b63-872262a89d98.png)

It seems to be on dialogs that have break lines, not sure if the sizing of the box is incorrectly set for spacer lines.

**Comment by NPBruce** [comment] 2017-11-18 03:02
Duplicate of #553

**Closed by NPBruce** 2017-11-18 03:02 UTC
