### ISSUE TITLE
Fall of House Lynch and Exotic Materials need balancing

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#317] opened 2017-04-24 06:56 UTC

**Comment by Hobbeslionheart** [comment] 2017-04-26 02:11
I played Exotic Materials with my girlfriend this evening and we enjoyed it. Great job and I loved using tiles that wasn't really used in the base scenarios. Some suggestions of balancing and improvement:

           - To help balance and add some excitement, add a monster every four-five rounds in the first phase and every two-three rounds in the second phase depending on number of investigators (trying to be vague to not spoil it).                  
      - Offering a second path particularly in the second phase would be an interesting choice if a puzzle is needed to solve it. Barricades should be place strategically.
     -   Also having additional explore tokens in the second phase might offer some interesting trade offs.

We'll try to test House Lynch soon.

**Comment by NPBruce** [comment] 2017-04-26 02:30
Thanks!

I assume you played with 2 investigators and won?  Can you give me an idea of how far off one of you was from eliminated?

I made a deliberate choice to keep it linear and simple because I wanted a short scenario (we have lots of long scenarios).  The trick is making it hard enough still.

My main controls point are:
* Moving the exit
* Changing how quickly Mythos ramps up (the events get worse the longer you take)
* Increasing Cultist health
* Making the custom second phase mythos events more punishing

I think I will do all of these a bit and maybe add some second phase reinforcements (don't really want to do this in the first phase, breaks the theme).

**Comment by Hobbeslionheart** [comment] 2017-04-26 02:44
We played with four investigators: two each. Two investigators were wounded and insane (the same investigators) and one was one damage away from being eliminated. I actually thought we would lose, but there were a lot of chokepoints and ranged weapons that we were able to attack from a distance (particularly the basement). Spawning reinforcements on the other side could potentially trap investigators forcing a choice of keep moving to stave off the other side, stay in an advantageous position where you might get trapped but overwhelmed as well as getting punished by the Mythos for waiting.

As for the linear nature, I guess that's the case, but it did seem like we were leapfrogging each other in the beginning. Once we understood the end game, it actually set up well. 

The exit could be moved a bit further, but unless there's additional monsters, it just prolongs the game and the only way one could lose is by a random mythos event.

**Comment by NPBruce** [comment] 2017-04-26 02:51
Sounds like I got it pretty close.  I will bump cultist health a little to disuade cleaning them all out.  Might leave everything else for now.

**Comment by NPBruce** [comment] 2017-04-26 03:07
When you play House Lynch, can you please save the game shortly before finishing and send me the vSave file?  That would help a lot.

**Comment by Hobbeslionheart** [comment] 2017-04-26 03:11
Sure!

**Comment by redwolf2** [comment] 2017-05-01 05:53
If you still can, check those in first. https://github.com/NPBruce/valkyrie-questdata/pull/3
https://github.com/NPBruce/valkyrie-questdata/pull/2

**Comment by eorahil** [comment] 2017-05-11 14:39
spanish forum user posted this after testing House Lynch Scenario:
It's translated and summarized:

> - Tested Lynch scenario with 2 investigators
> - Few orthographical and translation bugs (these are mine...).
> - Scenario don't scale up with more investigators. Less players should give IA less actions.
> - Starting item whisky but after I found a whisky exploring. There are not 2 whiskeis in game...
> - Exploration gives lot of "get 3 clues"... I think there are too much.
> - Font size is very small. Should be bigger or customizable.
> 
> SPOILERS FROM HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> - 1 first edition spawning Maniac costs 4 threat point and were dificult to have. Here there are maniacs one after another. It looks like a Maniacs "ZOMBIZIDE".
> - After exploring ALL tokens, the objective wasn't revealed being in a empty board. The Mithos phase was "A Maniac Appears and attacks". Kill, kill, kill
> -After a lot of kill kill rounds the objective is revealed and the objective is "Kill the maniacs!!!" A 6 turns kill bill movie!!
> - I got lot of weapons and wound and sanity cures. I was untouchable!!
> - Objective shouldn't be revealed only by time pass,but also by revealing all story about what happened Mr Lynch
> 

There were also lot of congratulations about the conversion, I omitted to get only the part to be revised.

**Comment by NPBruce** [comment] 2017-05-11 21:52
> Starting item whisky but after I found a whisky exploring. There are not 2 whiskeis in game...
Not sure why this happened, but 1.1 will change this whole system for the better.
> Font size is very small. Should be bigger or customizable.
The whole UI is based around this font size, which is consistent with FFG.  Not going to change at this point.
> 1 first edition spawning Maniac costs 4 threat point and were dificult to have. Here there are maniacs one after another. It looks like a Maniacs "ZOMBIZIDE".
It is actually pretty similar, in a 2 investigator game you would get them at most every second round, and the same applies here.
> After exploring ALL tokens, the objective wasn't revealed being in a empty board. The Mithos phase was "A Maniac Appears and attacks". Kill, kill, kill
-After a lot of kill kill rounds the objective is revealed and the objective is "Kill the maniacs!!!" A 6 turns kill bill movie!!
Not sure what happened here, but this is never the objective.  One story spawns many maniacs and you have to escape, another spawn Walter (a maniac) and you have to kill him.  Both of these should trigger on finding the last clue.  A save game would be helpful to see what happened.
> I got lot of weapons and wound and sanity cures. I was untouchable!!
This is consistant with the original, though I did remove one of the starting weapons recently (not sure what version was played).

**Comment by redwolf2** [comment] 2017-05-18 02:35
Fall Of House Lynch needs a place investigator token like Exotic Material.

**Comment by NPBruce** [comment] 2017-05-18 03:01
> Fall Of House Lynch needs a place investigator token like Exotic Material.
Done.

**Comment by Rass1968** [comment] 2017-06-11 11:30
We´ve played House of Lynch (German version) yesterday and it was quite fun but there are also some questions and bugs we found. I need to say that we are new to VdW. This was our third game and the first in Valkyrie. 

We love the way you integrated the Monster UI, better than the original.

Questions about Valkyrie itself

The Horror Test. In Valkyrie it seems you need to choose the Horror test it if you want or not manually. Right? But during the Mythos Phase it was unclear for us when the phase ends to choose the test.

When an Investigator is eliminated, the original app says hit the Button at the end of the next Investigator phase. In Valkyrie you need to hit the button directly when the elimination happens and the Scenario will end automatically at the end of the next Investigator phase?

Question Scenario 

One Investigator was Sister Mary and the Maniacs loved her. They always spawned on her field. Is there a reason for this?

Bugs, translation issues

There is a door which leads to the Garden. The token say “you need the right combination for the lock” (meaning in the German translation) What you need is the “Silver Key”, so the translation confuses.

There were several doors without any marker? Should this be that way?

--------------- Spoiler, maybe ;)-------------




The text for one Maniac says, “prevent him to gather more samples” (my translation from the German Version) at this point of the game it doesn´t make sense for us. 

As written before from eorahil we didn´t got the final clue too (I think it is the “Séance” where you find out what happened with Walter?) Save game could be send.

**Comment by NPBruce** [comment] 2017-06-11 11:48
Thanks for the report.

> The Horror Test. In Valkyrie it seems you need to choose the Horror test it if you want or not manually. Right? But during the Mythos Phase it was unclear for us when the phase ends to choose the test.

This is the same as the FFG app, the only difference is I am not displaying a message each round to tell you todo the test, is that what you mean?

> When an Investigator is eliminated, the original app says hit the Button at the end of the next Investigator phase. In Valkyrie you need to hit the button directly when the elimination happens and the Scenario will end automatically at the end of the next Investigator phase?

I'm still split on this.  I like the Valkyrie way better but it is inconsistent with the official App, so I might change it.

> One Investigator was Sister Mary and the Maniacs loved her. They always spawned on her field. Is there a reason for this?

It is random, she was unlucky.

> There is a door which leads to the Garden. The token say “you need the right combination for the lock” (meaning in the German translation) What you need is the “Silver Key”, so the translation confuses.

If someone provides a correction I will apply it.

> There were several doors without any marker? Should this be that way?

Are you talking about about door at the edge of the map that go nowhere?  Yes, this is intentional (not enough tokens to close off everything).

> The text for one Maniac says, “prevent him to gather more samples” (my translation from the German Version) at this point of the game it doesn´t make sense for us.

Where did this text occur?  It should have been either on a clock strikes 1 timed event or because you found the last clue (you say you didn't).  It means that the maniacs are trying to take samples from you (you should be getting tests) and you have to try to stop them (mostly just make sure you pass that test).  Once they have enough samples the objective will change, or if you go a few rounds without them getting samples you will win.

> As written before from eorahil we didn´t got the final clue too (I think it is the “Séance” where you find out what happened with Walter?) Save game could be send.

A save game would be great.

**Comment by Rass1968** [comment] 2017-06-11 12:53
Thanks for the report.

The Horror Test. In Valkyrie it seems you need to choose the Horror test it if you want or not manually. Right? But during the Mythos Phase it was unclear for us when the phase ends to choose the test.
> This is the same as the FFG app, the only difference is I am not displaying a message each round to tell you todo the test, is that what you mean?
Yes, because you didn´t say it you can miss it easy.
 
There is a door which leads to the Garden. The token say “you need the right combination for the lock” 
(meaning in the German translation) What you need is the “Silver Key”, so the translation confuses.
> If someone provides a correction I will apply it.
I tested it a few times and there are different events at this door. On one other door in this scenario is a hint that says you need the Silver key (the Silver key is needed for minimum two different doors in the scenario?), the same should be there, if I´m right.

The text for one Maniac says, “prevent him to gather more samples” (my translation from the German Version) at this point of the game it doesn´t make sense for us.
> Where did this text occur? It should have been either on a clock strikes 1 timed event or because you found the last clue (you say you didn't). It means that the maniacs are trying to take samples from you (you should be getting tests) and you have to try to stop them (mostly just make sure you pass that test). Once they have enough samples the objective will change, or if you go a few rounds without them getting samples you will win.
Not shure about, I think it was after a clock strike. The problem is what "take samples from you" mean, f.e. he want my heart, a part of my body? For what? That make no sense in the storyline that a Maniac (except Walter) want to do this or did he want me simply dead?

As written before from eorahil we didn´t got the final clue too (I think it is the “Séance” where you find out what happened with Walter?) Save game could be send.
> A save game would be great
enclose
[house_lynch_saveAuto.zip](https://github.com/NPBruce/valkyrie/files/1066427/house_lynch_saveAuto.zip)

You answer to quick so you miss my edit ;)
  The Back button (great idea), how many steps you can go back?

**Comment by NPBruce** [comment] 2017-06-11 12:56
> The Back button (great idea), how many steps you can go back?

I assume this refers to Undo, you can go back to either that start of the quest or when you loaded a save game (the undo state is not saved with save games).

**Comment by Rass1968** [comment] 2017-06-11 13:47
There were several doors without any marker? Should this be that way?

> Are you talking about about door at the edge of the map that go nowhere? Yes, this is intentional (not enough tokens to close off everything).

We had enough wall markers left in our game box to close the unused doors ;)

**Closed** 2017-11-13 21:59 UTC
Labels: enhancement, help wanted, Scenario
