### ISSUE TITLE
Not saving texts after update

### ISSUE THREAD

**Issue by prilogon** [NPBruce/valkyrie#517] opened 2017-06-08 17:57 UTC
I have been updated to 1.3, and selected portuguese language...

Now when I create a new token (or events, or other things) and I write on the dialog box and click in SAVE, the program erase the text I wrote on the dialog box

This not happens in new scenarios.

**Comment by cbusbird** [comment] 2017-06-08 20:34
Sounds like an issue I have been having.  Check the tokens.ini file in the scenario folder.  Does the token have "display=0" listed under it?

**Comment by NPBruce** [comment] 2017-06-08 20:56
I think this is a bit of a different issue.  My guess is the Portuguese language file isn't being created correctly.  I will investigate, but try manually creating Localization.Portuguese.txt and adding it into quest.ini with the other languages.

**Comment by NPBruce** [comment] 2017-06-22 03:49
I can't reproduce this.  Can you please explain in more detail the steps to create the problem?

**Comment by prilogon** [comment] 2017-06-22 13:18
I had a scenario created on 1.2 version. After update and change to portugueses, this scenario dont save texts in the dialog box.
I created a new scneario and started agains (this problem just happened with the old one)

**Comment by NPBruce** [comment] 2017-06-22 21:06
Can you please upload the scenario that didn't work?

**Comment by NPBruce** [comment] 2017-11-13 21:40
Closing as unable to reproduce.

**Closed by NPBruce** 2017-11-13 21:40 UTC
Labels: bug
