### ISSUE TITLE
Version 11 not showing in Valkyrie 2.4.02. Also, 5 heroes?

### ISSUE THREAD

**Issue by Xyphistor** [NPBruce/valkyrie#1194] opened 2019-08-16 23:10 UTC
### Description of Problem or Question
Quest (with nested subquests) doesn't appear in Valkyrie 2.4.02 with all versions set to v11.
Changing top level quest version to v10 doesn't fix it.
Changing top level and one of the others to v10 makes it appear in Valkyrie (both New Game and Quest Editor). Once Valkyrie has seen it, I can go back to main menu without closing Valkyrie, edit the quests back to format 11 and Valkyrie can still see them until it's closed and restarted...

This is the same quest where I have been able to select 5 heroes...

### Valkyrie Version
2.4.02

### Attach Save, Quest or Scenario
Quest files attached
[Into the Underdark.zip](https://github.com/NPBruce/valkyrie/files/3511362/Into.the.Underdark.zip)

**Comment by NPBruce** [comment] 2019-08-16 23:56
Version issue fixed in 2.4.03.

Cannot reproduce the 5 heroes bug in the attached scenario. If you have one that shows it, please raise a new issue for this.

**Closed by NPBruce** 2019-08-16 23:56 UTC
