### ISSUE TITLE
SOA - Minor Misspellings Person Tokens

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1235] opened 2020-01-07 09:57 UTC
Two of the names of the person tokens in SOA are spelt wrong.

Dew Walker should be Drew Walker
Naomi O'Bannon should be Naomi O'Bannion 

What would be great is if the names could be replaced with images but correcting the spelling would be worth doing as some players have raised complaints about spelling errors.

**Comment by redwolf2** [comment] 2020-01-07 15:29
The problem is with the texture. 

https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/StreamingAssets/content/MoM/soa/img/SpriteAtlasTexture-token.png

Will fix this soon.

**Comment by redwolf2** [comment] 2020-01-30 23:41
I did a pull request https://github.com/NPBruce/valkyrie/pull/1244

**Comment by BenRQ** [comment] 2020-04-18 19:02
Merged and delivered in 2.4.07

**Closed by BenRQ** 2020-04-18 19:02 UTC
Labels: MoM2E, bug
