### ISSUE TITLE
Exception when opening Editor

### ISSUE THREAD

**Issue by dlgreenwald** [NPBruce/valkyrie#23] opened 2016-09-16 12:02 UTC
When editing a Mansions of Madness scenario (or creating one) all you get is a black screen.

**Comment by NPBruce** [comment] 2016-09-16 12:19
I don't get this, what version are you using?  Can you please attach a log?  Do you get any interface buttons at all?

Haven't said that MoM support should be considered experimental at this stage, it should be OK to play around with, but I wouldn't recommend seriously using it just yet.

**Comment by dlgreenwald** [comment] 2016-09-16 12:23
I get no interface buttons at all.  Looking at the log before attaching it, it looks like a NPE is being thrown.  I'm using 5.1  


[output_log.txt](https://github.com/NPBruce/valkyrie/files/476790/output_log.txt)

**Comment by NPBruce** [comment] 2016-09-16 12:43
Interesting, I can't reproduce this or see anything obvious.  If I don't come up with something when I get back to working on MoM I'll add in some diagnostics.  Does Descent work?

**Comment by Liquidlogic1** [comment] 2016-09-16 12:54
Does he have the ffg MoM app installed? If not, you get black screen.

**Comment by NPBruce** [comment] 2016-09-16 13:05
You shouldn't, you should get a red import button and no further.  Also the log says he has MoM 1.0.4, which is correct.  Are you saying it crashes if MoM isn't installed?  Does this stop use of Descent?

**Comment by dlgreenwald** [comment] 2016-09-16 13:16
I have ffg MoM and D2E installed an both are imported.  The Descent section of the application is not working as well.  Nor can any quests be loaded, same symptom.  NPE and a black screen.

**Comment by NPBruce** [comment] 2016-09-17 04:16
Still haven't found anything but there are some cleanups in this area in 0.5.2.  Can you please try again and attach the log?

**Comment by Liquidlogic1** [comment] 2016-09-21 04:20
I think I found the reason for black screen.  I just installed ffg's MoM steam app, imported to Valkyrie and then went to editor and immediately got black screen.  I forgot to click the 'select content' button and select the core set.  This fixed the black sceen.  What is interesting, is that if you then go back and deselect all the content you wont get black screen any more. 

To replicate the issue- uninstall/delete Valkyrie. Reinstall fresh and import content. Then go directly to Start Scenario or Scenario Editor. You should get black screen.  Now go back and 'Select Content' and it should fix it.

**Comment by NPBruce** [comment] 2016-09-21 09:08
Excellent, found the problem will fix in a new release soon.  FYI deleting Valkyrie alone may not reproduce this, deleting the config file from %appdata% will.  Also you can't turn the base content off, but if the config file doesn't exist the editor will crash.

**Comment by NPBruce** [comment] 2016-09-22 05:36
This should be fixed in 0.5.3, if the problem still happens please reopen.

**Closed by NPBruce** 2016-09-22 05:36 UTC
