### ISSUE TITLE
Tome of Horrors - only considered equipment

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1300] opened 2020-05-26 12:10 UTC
The Tome of Horrors item in Mansions of Madness doesn't fall under the "Tome" category.  Instead, it is considered equipment.  Is that something that can be fixed?

Thanks!

Valkyrie Version 2.4.07

**Comment by redwolf2** [comment] 2020-05-26 19:36
I am on it

**Comment by redwolf2** [comment] 2020-05-26 19:44
Its not a bug, its on the card.

![grafik](https://user-images.githubusercontent.com/4141621/82943524-0ff95580-9f9a-11ea-887e-f66d31c23652.png)

**Comment by strategywizard** [comment] 2020-05-26 22:43
Interestingly enough, my copy of the card shows the "Tome" designation.  I bought my copy of this expansion late last year, so maybe the newer printings updated it to a "Tome" instead of "Equipment."

![Tome Of Horrors](https://user-images.githubusercontent.com/65921164/82957309-4b832800-9f78-11ea-8ed7-fffc92b031a3.jpg)

**Comment by redwolf2** [comment] 2020-05-28 18:36
I will look into this. Maybe there is some published errata available

**Comment by redwolf2** [comment] 2020-05-28 19:02
I made the changes https://github.com/NPBruce/valkyrie/pull/1302

**Comment by strategywizard** [comment] 2020-05-28 21:26
Thanks, redwolf2!

**Comment by scrubbless** [comment] 2020-06-02 13:02
Thats an odd one from FFG, I guess that was an early version printing error?

**Comment by BenRQ** [comment] 2020-09-21 21:26
Will be in 2.4.10

**Closed** 2020-09-21 21:25 UTC
Labels: MoM2E, bug

**Comment by EwenDC** [comment] 2021-03-13 00:40
I reported this in #1133 as well as a different classification issue with the Tome of Secrets card from the same expansion. Has that issue been fixed too?
