### ISSUE TITLE
Improve UI for online and offline mode

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1037] opened 2019-02-01 16:33 UTC
A locally created scenario (named Scenario 1) is not visible in the online mode while it's in offline.
![image](https://user-images.githubusercontent.com/7532602/52111760-7651ba80-2669-11e9-8746-8e09a9dd4272.png)

## Valkyrie Version

2.2.20190131

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1033#issuecomment-459646508_

**Comment by BenRQ** [comment] 2019-02-01 17:39
This is working as designed. You have to switch offline to see local quests.

I'm not saying it's perfect, but showing local quest would delay display a lot as it is.
Asynchronous loading of the full list is the best solution but requires a bit of work.

**Comment by BenRQ** [comment] 2019-02-02 00:14
Good news, I've been able to make asynchronous loading work.
This makes a huge difference in term of responsiveness.

I still don't know how I will merge online and offline list dynamically though.

**Comment by redwolf2** [comment] 2019-02-02 00:31
Maybe instead of one button that switches use two and let them act like tab headers, that allow to switch between a online and offline scenario list.

**Comment by BenRQ** [comment] 2019-02-02 00:35
Online and offline have different data structure, different sort method.
It's not simple to merge them.

I like your proposal @redwolf2, the idea of having both mode title displayed, and you select the one you want.
We don't have much space for tabs, but we could still use the top right corner to display the "two modes".
Selected mode would be highlighted somehow.

**Comment by BenRQ** [comment] 2019-02-02 00:36
@redwolf2, try the "sort by author", or "sort by update date".
I'm already using list headers there.

**Comment by redwolf2** [comment] 2019-02-02 00:38
I will do. If space is a problem, you could consider removing the title entirely. It should be pretty obvious, what this dialog does.

**Comment by scrubbless** [comment] 2019-02-02 15:50
I don't mind the offline mode option personally. We'd only need it to test, copy and scenarios offline.

Most of the time we want people in online mode playing new content.

**Comment by chrismaliszewski** [comment] 2019-02-03 21:44
So, first of all, I don't really understand the causes behind having two different data structures for online and offline. The structure should be identical but both could differ in terms what data they have initialized, i.e. online has statistics (offline doesn't) while offline has, I can't think of anything but, something that online doesn't have. 

This change for 100% should be made. Not only it will be easier to maintain data & code but also will allow other things to exist such as displaying one list of every scenario and filtering/sorting them. The structure would also make offline/online mode switching obsolete as a user would be able to sort/filter scenarios which are offline/online. 

But this is a major change so maybe in v2.3 :).

For now...

**Comment by chrismaliszewski** [comment] 2019-02-03 21:59
I'd suggest doing something a little bit else than it's now.
1. I'd urge to getting rid off switching between offline/online mode as it creates more confusion than good, I think. 
2. Next, I'd create a text which just indicates if a user is online or offline and...
3. a refresh button to check the status of the internet as well as update the 2. text and refresh a list of available scenarios. 
4. Next change would be displaying scenarios by either creating tabs or grouping scenarios based on wheater a scenario is offline one (created on the local machine) or online (downloaded from the Internet). Nothing else changes, I mean, display online scenarios with or wo. statistics whether a user is on- or offline. Offline scenarios are always displayed in the same way. 

So a majority of things created for now stays but a way of displaying scenarios and a refresh button are new. The button could be used in the future versions as its functionality shouldn't change ever if created properly.

**Comment by chrismaliszewski** [comment] 2019-02-05 23:36
I think I wrote this comment before the newest build and was worried about the offline/online mode. 

Now it's SO MUCH BETTER in terms of responsiveness so the above ideas can wait for the v2.3 or another one.

**Comment by BenRQ** [comment] 2019-02-05 23:37
OK cool 👍

**Comment by BenRQ** [comment] 2019-02-26 20:10
I will close this issue, as a lot of things have moved since it was opened.
Anyone can open a new ticket if you think we should improve some part of the scenario explorer.

**Closed by BenRQ** 2019-02-26 20:10 UTC
Labels: ScenarioExplorer, enhancement
