### ISSUE TITLE
Create "COPY" for tiles/events/tokens in Valkyria

### ISSUE THREAD

**Issue by FASTNAVi** [NPBruce/valkyrie#756] opened 2018-01-23 21:26 UTC
Hi,

I am making scenario for MoM2 and I was thinking about some kind of COPY command.

I will try to explain what I mean. First, I make TILE0, EVENT0 and TOKEN0. For example. And then, I put inside them some texts, buttons, logic tests and assigns etc. like usually. Then, I need to make their copies, meaning everything be the same (position, texts....) just with different name, for example TILE0_copy, EVENT0_copy, TOKEN0_copy. Then I can just change some details like tests and buttons..

Right now when I like to do something like this, I make original ones, then open some notepad and copy all text and note all logic tests and assigns and buttons with events. Then I need to make new ones, making them on the same position, copying all texts from notepad, making all tests and assigns and buttons with events on my own. When will be some kind of copy command, then it will save my time a lot.

I hope you understand my problem. I was also thinking about copying things directly in text editor, just with changing name.. but I don't know how difficult will be this way.

So I hope somebody will know how to find solution of my issue :)

EDIT: Or at least will be possible to make in Valkyria some kind of "texts memory"? In my work I have one.. just click CTRL+1 and text it is save as text "1".. then i can save up to 10 texts in one time.

Or it is possible to have one window with graphic part as ussual but two windows with events/tokens/tiles settings, so I can see two different things at once?

**Comment by LordPyrex** [comment] 2018-01-24 22:54
I don't know that this has been considered for any implementation. The reason being is that each event controls it's own functions. Are you making copies because you are trying to provide multiple paths? Are you trying to make copies to remind yourself how the logic works?

If you're in need of a copy as a way to show your logic flow then I would recommend writing everything in a text editor so that you can piece it like together like a tree. Copy and Paste works from one program to the other. Otherwise I'm not sure what else you need to copy.

**Comment by NPBruce** [comment] 2018-01-24 23:12
This is very hard to do well because there are so many connections between the components.

I would consider first creating an editor mode that shows a map of all components and how they connect to each other.  It might then be possible to duplicate a section of the map, maintaining connections external to the selection.

This is a 'maybe one day' type feature at this point.

**Comment by FASTNAVi** [comment] 2018-01-24 23:35
I understand. No hurry, so far it is not imminent issue. Thank you for response.

I am doing copy of existing things for example for multiple places (depending on var) of obtaining one item. So I need to copy token (just change name of following event and position) and event to show him (change name of token, change tests conditions - usually just number in var - and of course make other event to start this one). Well, so far is maybe better for me to make them all by myself, because I can check everything.. just need to use ctrl+c and ctrl+v several times (using notepad next to valkyria).

But I have plans for more scenarios in my head and especially one of them trully need some kind of copy. I don't want to free share my ideas but for example: I will make some room with tokens and events.. totally for example, 10 things or more. And I want to use the exactly same room 2 times in my scenario - of course not in the same time. So I just need copy all of them, change names and position and voila, I am done. Then I can very easy check everything and change some variables.. Just work for 5 minutes insteed of 20 or more, when I need to make all 10 things once more again. And also with copy command is just small chance that I will do something wrong during remastering this room. This is just for example. Also I can used copy command to make several layouts of my map very easy and quick. You know, first time is kitchen on left, next time on right and so on.. Well so far I will try to experiment with copying all needed directly in ini files. Hopefully it will works.

Nevermind, I am almost done with my first scenario. I just need to test it many times and also translate it to englisch. So it will be here to the end of next month, I hope =)

**Comment by NPBruce** [comment] 2018-01-24 23:38
A lot of this sounds like it would be better served by making the component position a var, rather than copying.

**Comment by FASTNAVi** [comment] 2018-01-24 23:58
NPBruce: Sorry, I don't follow your advice. How you mean "the component position a var"? It is possibly to do that right now in Valkyria?

**Comment by NPBruce** [comment] 2018-01-25 00:19
No it isn't, just suggesting that maybe that is a better way to implement what you want?

**Comment by FASTNAVi** [comment] 2018-01-25 00:30
Yeah, but this is not resolving my issue. I still need to make copies of these tokens, tiles, events by myself. Directly in Valkyria or in ini files. It will take some time.

Well nevermind. Like I said, I will maybe need this in distance future. And if it will not be copy command there, I will try my luck with some type of clever copying in ini files =)

**Comment by NPBruce** [comment] 2018-04-23 03:02
Closing as duplicate of #522.

**Closed by NPBruce** 2018-04-23 03:02 UTC
Labels: enhancement
