### ISSUE TITLE
Can't open file in editor after a save

### ISSUE THREAD

**Issue by Crispy66** [NPBruce/valkyrie#646] opened 2017-11-04 02:32 UTC
New user here, and not very experienced with programming.
I love the interface, and have been working on a trial scenario.  All was well - I had about 4-6 hours in and have learned a lot.  I had just made some changes intended to cause a custom monster to spawn after a set number of turns.  I hit 'save and test' and everything froze.  I got the (not responding) prompt in the upper left of the window.  
I had Firefox open, and I noticed that it was also running very slowly.  I tried to close Firefox and GIMP, and the whole system seemed to be running very slowly.  Eventually I exited all of my programs, and got an error window that said "Windows has stopped working" - never seen that one before.  Anyway, I did a restart and ran Avast.  No problems found.  
I restarted Valkyrie, and my file is still listed in the scenario menu and in the editor menu, but when I click on it to open, it just goes back to the menu.  If I load it as a saved game, it opens shortly in (after 2 tiles have been placed), and plays normally.  I just can't edit it, or start at the beginning.
As I said, I am rather inexperienced at coding, but I understand the basics of how things work.  I'm not sure how to proceed here; I can start over, but I'd really like to know what happened.  It is possible that I just hit a big slowdown due to other programs open, but I've never seen one this bad before.  I shut down Valkyrie by closing the window, not using the Exit button, so I know I may have just corrupted the files, but I don't know how to evaluate that.

**Comment by NPBruce** [comment] 2017-11-04 02:50
Sounds like you hit an editor bug that broke your scenario.  Can you please upload your scenario which will let me see how it is broken, and I'll likely be able to fix it for you.

Also you can extract the scenario from the save game file (unzip it) to get the version from whenever the save was made.

**Comment by Crispy66** [comment] 2017-11-04 03:19
That sounds great.

I don't know where the save files are.  I have a folder on C:\Program Files (x86)\Valkyrie, but I don't recognize anything in it or subfolders as save files.  Where are they?

**Comment by NPBruce** [comment] 2017-11-04 11:12
The scenario will be in:
%AppData%\Roaming\Valkyrie\MoM\Editor

And save games in:
%AppData%\Roaming\Valkyrie\MoM\Save

**Comment by Crispy66** [comment] 2017-11-09 23:16
I have the scenario working again - I opened a new file, then gradually transferred the .ini files over.  I didn't lose much info, but have no idea what caused the crash.

**Comment by NPBruce** [comment] 2017-11-09 23:28
I'll try to look at this soon for 1.6 fix.

**Comment by NPBruce** [comment] 2017-11-13 08:58
The problem is here:

[SpawnEdith]
monster=MonsterGhost
traits=undead horror

There are no monsters that are undead, horros and not Ghosts.

Better error reporting will be part of #661

**Closed by NPBruce** 2017-11-13 08:58 UTC
Labels: bug
