### ISSUE TITLE
Quenstions/Enhancement: Knowing players' location in the game 

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#989] opened 2018-12-20 07:10 UTC
### Description of Problem or Question
I'm thinking about creating a scenario. I have an interesting idea but it requires information about the players' location on board so the app would be able to say "a player is alone in a specific room". 

I have a few questions which could help resolving the problem for me: 
1. is it possible with the current version of the app to create a token which would be moveable by a player, i.e. by dragging and dropping it? (this would be the easiest way)
2. is it possible with the current version of the app for a player to create a token on a fly during a game? (or is it possible only in the editor)
3. if both above questions are false, do you have any other idea how it could be achieved without creating a new functionality?
4. does the game recognises a location of tokens in terms of in which room they are in? (or they are just put in XY position and thing else is known)
5. if the above is "no", is it possible to get a tile's borders locations as well as width & height to check above by calculations?

If nothing from above is possible right now, what do you think about creating this kind of functionality? As I said, I can think about many possible new ways of arranging stories by having this information in the game! Not only plot changes or twists but also interesting environmental riddles!

Let's have a discussion, shall we? :)

**Comment by scrubbless** [comment] 2018-12-20 12:08
There is not functionality to track players without direct interaction with the player. The reason for this is players move at different rates and in a multitude of directions.

Adding functionality to track a players location is going to make the game too complicated and cumbersome to play.

Tokens are deployed independently using coordinates, they are not linked to tiles at all.

You can roughly track where a player is based on tokens that have been used and tiles that have been placed.

So if you want an event to hit a tile with a player with fairly certain accuracy you could create an assignment for every event on each token, that puts the round in the variable.

For example.

You have tiles,

Tile 1 has token A and B
Tile 2 has X and Y

When a player uses the token A we assign a variable when the event triggers (because we know the player is at least 3 spaces from that token they used an action on). We say Tile1Var == #round.

We can then have a mythos event that triggers based on that:


Mythos events selected at random:
Event1
Test:
Tile1Var == #round = Run a Tile 1 specific event

Event 2
Tile2Var == #round = Run a tile 2 specific event


The example above will allow events to run some if players have interacted with a token on a tile.

Toy could add these variatles to every token in the game tying it to one or more tiles.

**Comment by chrismaliszewski** [comment] 2018-12-20 18:31
I understood from the very beginning of having the game why the app doesn't require tracking players' exact locations. But I hoped something like that would be possible to be achieved by using some tricks in Valkyrie. 

To my thinking, the movement of players would be recorded any time in an investigator's phase by any of investigators. So it wouldn't be that annoying, especially, when it'd give players something in return: new ways of entertaining them.

For example, I have an idea of giving players items but only from a certain NPC (each player with a different one) which they need to find and only when they are alone in a room with the NPC. It'd be like a secret meeting plotting or not against others. 
Unfortunately, it's unachievable without either knowing players' exact locations or by directly asking players to whom the NPC wants to talk which but the latter would destroy the concept of a surprise and plotting. 

Other possibilities are environmental riddles, i.e. in the riddle, multiple rooms are used but players can only be present only in one room at a time; other rooms must be unoccupied. Although I see a possibility to achieve it by players' interactions (with asking people if they are in other rooms), variables and tricks (creating one-way-doors to the rooms and counting people in the rooms). But it'd also destroy a mood and fluidity of the gameplay and, possibly, give hints about the riddles as well as a possible way to solve them. 

**The final question**. I'd like to confirm again one thing which I asked but there was no answer to this question: can players during a game interact with a token (it'd be a character token) and, as a result of the interaction, fire an event allowing them to click in another position on the game board which would cause the token to appear in the clicked location? 

Do you think this kind of ideas are too complicated for the game? Or do you have any idea how to achieve them with the current possibilities which would be enjoyable?

Thank you, @scrubbless, for your help!

**Comment by redwolf2** [comment] 2018-12-20 18:43
> I'd like to confirm again one thing which I asked but there was no answer to this question: can players during a game interact with a token (it'd be a character token) and, as a result of the interaction, fire an event allowing them to click in another position on the game board which would cause the token to appear in the clicked location?

You can have a dialog with choice options and tokens appearing with based on those options. But you can't have token appear at mousecursor positions.

I think this request is out of scope. The official app does not allow this as a design choice. What happens on the board comes first. The whole game mechanic could be done inside the app. I think it is intended by design not to track the player movements on the board, but use tokes for it.

**Comment by chrismaliszewski** [comment] 2018-12-20 19:03
I think FFG did that to
1. force people to buy the board game so they won't be able to play it without it,
2. it'd require much more work (and money) to implement it,
3. (as we said earlier) people would need to interact more with the app which could be not enjoyable.

For the described purposes, the choice options are not enough as you can imagine :(. It wouldn't be fun but rather frustrating. 

**BUT** you have a point with the interaction markers placed on the board from the beginning! In-house rules could assign a character token to each player and only the player would be allowed to interact with! Yeah, that'd be a solution for the first idea which would be good enough, easy to play and wouldn't destroy the experience.

For the environmental riddles, tricks (like the ones I described above) and choice options could be used so that's not a big issue. 

Thank you, @redwolf2! Thank you, @scrubbless!

I think as there is no time, resources nor need to create such enhancements, could someone please close the topic? I think everything that was possible to be said at the moment was said :).

**Closed** 2018-12-20 19:03 UTC
