### ISSUE TITLE
Custom horror checks?

### ISSUE THREAD

**Issue by Ocirus** [NPBruce/valkyrie#448] opened 2017-05-19 22:18 UTC
Hey, I've been crafting a scenario in MoM (so far: GREAT tool) but **I can't seem to figure out how to do custom horror checks. Is it possible?** I've checked through the tutorials in the Wiki and haven't found anything.

Basically I have custom monsters and am using a Ghost as a base for the piece. I have already figured out how to do custom attacks during the Mythos phase, but when I go to do a horror check it still using very ghost/spirit-like language. Am I just missing something entirely? Sorry to clutter the issues section if this is, in fact, not an issue.

**Comment by NPBruce** [comment] 2017-05-19 22:27
Unfortunately custom evade and horror checks are not yet supported. Closing as duplicate of #146.

**Closed** 2017-05-19 22:28 UTC

**Comment by Ocirus** [comment] 2017-05-19 22:33
Thanks for letting me know, and apologies for not seeing the dup. Guess I'll just deal with the weirdness for now, and I look forward to more updates. Thanks again for all the hard work!
