### ISSUE TITLE
Bug: audio doesn't stop playing in the BG

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#979] opened 2018-12-10 23:16 UTC
### Description of Problem or Question
It's a general issue. After you choose a scenario with a narrator audio at the beginning of the scenario and decide to and scenario, the audio keeps playing instead of being ended. This creates another issue when you start another (or the same scenario) with an audio again as both sound overlap. You can go on and on with that procedure.
To me, the audio should even end after you click Continue instead of playing it further.

### Scenario to replicate:
-Click Start Scenario, 
-Choose any scenario with a narrator at the beginning (i.e. A Glimpse of the Past), click Start, choose any characters, click Finished twice,
-While the narrator audio is playing, click Menu -> Main Menu,
-The audio keeps playing
-(*optional) Repeat the whole Scenario to create overlapping sounds.

### Valkyrie Version
2.15 (Windows 10 but presumably also other systems)

### Suggestion
Force stopping a narrator audio after going to another section of the app; it doesn't matter if you click Continue or go back to Main Menu.

**Comment by BenRQ** [comment] 2018-12-11 20:04
Hi @chrismaliszewski ,

I agree with you, audio should stop when leaving the scenario and going back to menu.

But when going through events in the scenario, I'm not sure it makes sense to just stop any playback at every event startup.
It would be a big constraints for scenario authors if we were to stop it like that.

Maybe we could try to find a way to control playback, but that's an evolution we need to think about it.
 
@scrubbless I'd be happy to hear your thoughts on that, as you are a heavy audio user in your scenarios.

**Comment by scrubbless** [comment] 2018-12-12 09:03
I disagree that sound should end when clicking continue. I actually use this in my latest scenario. There is a use case to layer sounds.

Story narrative should be put as music. That way you can control it by replacing the music in another event. 'audio' should only be used for short sound bites.

**Comment by BenRQ** [comment] 2018-12-13 20:03
So to summarize the issue here: the only change we should implement is to stop music/audio when leaving the quest.

Please correct me if I understood this wrong.

**Comment by chrismaliszewski** [comment] 2018-12-13 20:11
Taking into account what @scrubbless said, yes, this should be the only change. 

Something still bothers me. If you play a scenario over and over again (no matter the reason) and you have enough of the narrator's audio, in my opinion, you should be able to stop it. So my question is, would it be possible to create some way to do that? To my thinking, there could be a control that enables a player to turn the audio off. 

I'm not saying 'do that now'. Just put the idea into a shelf for a future release when there is nothing important to be done.

**Comment by scrubbless** [comment] 2018-12-13 22:09
We should urge scenario creators to set narrated intros as music. Then the event after set the music for the scenario.

Run stress and strain. If you click start before the narrative finishes it will stop it.

**Comment by chrismaliszewski** [comment] 2018-12-13 22:19
I see. So it will be put on the shoulders of creators then and hope they will do as you say. 

Does it mean nothing would need to be done if creators did as you say in the first place? I mean, the bug wouldn't have a place if they used the technique which you've just described, right? If that's so, it's not exactly a bug but rather an issue of implementation. 

Still, I'd urge a full-stop of any sound of a scenario after exiting it, just in case to prevent other unexpected problems to happen.

**Comment by scrubbless** [comment] 2018-12-14 16:42
Yeh, exiting the scenario or the editor should stop all audio. I agree.

**Comment by BenRQ** [comment] 2018-12-16 12:36
I've made sure audio effects are stopped at the end of a scenario.
Fix will be available in release 2.2.

For Glimpse in the past, maybe we can tell the author to check if he wants to change how he plays the audio of the intro. 

@slycozzolino we are talking about you :)
BTW, if you want to have access to players feedback on your scenario, it is now available !
Have a look here : 
https://docs.google.com/spreadsheets/d/1OsevlouIvR0DRYhGIS41PU9lBLB8VYgJvyj9KsHcAik/edit#gid=517646170
I can also share the raw file, where you can see the list of events as they happened for each play session.

**Comment by BenRQ** [comment] 2018-12-16 12:37
(closing the issue as the problem is now fixed in Valkyrie)

**Closed by BenRQ** 2018-12-16 12:36 UTC
Labels: bug

**Comment by slycozzolino** [comment] 2018-12-17 04:53
@BenRQ Do I still need to fix this in my scenario?

**Comment by BenRQ** [comment] 2018-12-17 08:16
Yes, if you can fix it as Scrubbless has explained, it will stop voice playback if player wants to skip that part.
