### ISSUE TITLE
Valkyrie crashes when I try to download an adventure

### ISSUE THREAD

**Issue by rubensemp** [NPBruce/valkyrie#396] opened 2017-05-06 14:49 UTC
I have Steam and the official app for MOM installed and I have imported the content from the app, but when I click on DOWNLOAD in the START SCENARIO menu the program crashes. Any solution please? 
And thanks a lot for Valkyrie NPBruce! ;-)

**Comment by eorahil** [comment] 2017-05-06 17:46
Please provide the log file to see the crash reason
if you have windows it can be found here:
C:\Users\[yourwindowsuser]\AppData\Local\Unity\Editor\Editor.log

**Comment by rubensemp** [comment] 2017-05-06 17:49
I don't have a Unity folder in that path. Thanks for yor response!

**Comment by NPBruce** [comment] 2017-05-06 21:39
It will be in Valkyrie_Data\output_log.txt in whereever you put Valkyrie.

As a work around you can download the .valkyrie files from here:
https://github.com/NPBruce/valkyrie-store/tree/master/MoM

And place them in C:\Users\Bruce\AppData\Roaming\Valkyrie\Download

**Comment by rubensemp** [comment] 2017-05-06 22:24
I've copied the file "TheFallofHouseLynch.valkyrie" in "C:\Users\<username>\AppData\Roaming\Valkyrie\Download" but it doesn't appear in the START SCENARIO menu

**Comment by rubensemp** [comment] 2017-05-06 22:25
And this is my outpot_log.txt

Initialize engine version: 5.5.1f1 (88d00a7498cd)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: Radeon (TM) RX 480 Graphics (ID=0x67df)
    Vendor:   ATI
    VRAM:     3072 MB
    Driver:   21.19.525.258
Begin MonoManager ReloadAssembly
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\FFGAppImport.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\FFGAppImport.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Ionic.Zip.Unity.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Ionic.Zip.Unity.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\ValkyrieTools.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\ValkyrieTools.dll into Unity Child Domain
- Completed reload, in  0.033 seconds
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\System.dll (this message is harmless)
desktop: 1920x1080 60Hz; virtual: 1920x1080 at 0,0
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.088449 ms
Valkyrie Version: 1.0.1

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
Asset location: /Road to Legend_Data
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find main assets file: /Road to Legend_Data/resources.assets
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG D2E not found.

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Asset location: C:\PROGRAMAS\Steam\steamapps\common\Mansions of Madness/Mansions of Madness_Data
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG MoM Version Found: 1.3.3

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\content\D2E\ffg\import.ini".
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 8b4 -> priority: 1 
  Thread -> id: 1150 -> priority: 1 

Unloading 4 unused Assets to reduce memory usage. Loaded Objects now: 473.
Total: 0.534876 ms (FindLiveObjects: 0.030794 ms CreateObjectMapping: 0.019796 ms MarkObjects: 0.476952 ms  DeleteObjects: 0.005865 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 527.
Total: 5.084806 ms (FindLiveObjects: 0.037027 ms CreateObjectMapping: 0.028595 ms MarkObjects: 4.990589 ms  DeleteObjects: 0.027495 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 528.
Total: 4.344631 ms (FindLiveObjects: 0.037027 ms CreateObjectMapping: 0.022362 ms MarkObjects: 4.281942 ms  DeleteObjects: 0.002932 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Warning: Unable to read file: C:\Users\RUBEN\AppData\Local\Temp\Valkyrie/TheFallofHouseLynch.valkyrie
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)


Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 448.
Total: 4.568993 ms (FindLiveObjects: 0.028595 ms CreateObjectMapping: 0.019063 ms MarkObjects: 4.516202 ms  DeleteObjects: 0.004765 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 6 unused Assets to reduce memory usage. Loaded Objects now: 528.
Total: 4.172327 ms (FindLiveObjects: 0.027495 ms CreateObjectMapping: 0.020163 ms MarkObjects: 4.100473 ms  DeleteObjects: 0.023462 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 529.
Total: 4.252614 ms (FindLiveObjects: 0.040693 ms CreateObjectMapping: 0.022729 ms MarkObjects: 4.183325 ms  DeleteObjects: 0.004765 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)


Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 885.
Total: 4.844680 ms (FindLiveObjects: 0.049858 ms CreateObjectMapping: 0.037393 ms MarkObjects: 4.692906 ms  DeleteObjects: 0.064155 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 885.
Total: 4.454979 ms (FindLiveObjects: 0.043992 ms CreateObjectMapping: 0.029328 ms MarkObjects: 4.377992 ms  DeleteObjects: 0.003299 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 18 unused Assets to reduce memory usage. Loaded Objects now: 528.
Total: 4.391557 ms (FindLiveObjects: 0.035927 ms CreateObjectMapping: 0.020163 ms MarkObjects: 4.309071 ms  DeleteObjects: 0.025662 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 529.
Total: 4.272044 ms (FindLiveObjects: 0.036660 ms CreateObjectMapping: 0.021629 ms MarkObjects: 4.208254 ms  DeleteObjects: 0.004765 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Warning: Unable to read file: C:\Users\RUBEN\AppData\Local\Temp\Valkyrie/TheFallofHouseLynch.valkyrie
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)


Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 449.
Total: 4.185892 ms (FindLiveObjects: 0.021263 ms CreateObjectMapping: 0.019063 ms MarkObjects: 4.139699 ms  DeleteObjects: 0.005132 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 7 unused Assets to reduce memory usage. Loaded Objects now: 349.
Total: 4.148131 ms (FindLiveObjects: 0.022729 ms CreateObjectMapping: 0.018696 ms MarkObjects: 4.039616 ms  DeleteObjects: 0.066722 ms)

Failed to connect to raw.githubusercontent.com port 443: Bad access
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 346.
Total: 0.499315 ms (FindLiveObjects: 0.019063 ms CreateObjectMapping: 0.032627 ms MarkObjects: 0.422695 ms  DeleteObjects: 0.024195 ms)

**Comment by eorahil** [comment] 2017-05-06 22:37
I don't see the crash in this file. Did you get this log just after the crash?
You should open Valkyrie, Start Scenario, Donwload. After this you sayd the app crasses. Just at this moment copy the log file and put it here.

**Comment by rubensemp** [comment] 2017-05-06 22:43
This is just after the crash:

Initialize engine version: 5.5.1f1 (88d00a7498cd)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: Radeon (TM) RX 480 Graphics (ID=0x67df)
    Vendor:   ATI
    VRAM:     3072 MB
    Driver:   21.19.525.258
Begin MonoManager ReloadAssembly
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\FFGAppImport.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\FFGAppImport.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Ionic.Zip.Unity.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\Ionic.Zip.Unity.dll into Unity Child Domain
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\ValkyrieTools.dll (this message is harmless)
Loading C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\ValkyrieTools.dll into Unity Child Domain
- Completed reload, in  0.036 seconds
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\Managed\System.dll (this message is harmless)
desktop: 1920x1080 60Hz; virtual: 1920x1080 at 0,0
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.019527 ms
Valkyrie Version: 1.0.1

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
Asset location: /Road to Legend_Data
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find main assets file: /Road to Legend_Data/resources.assets
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG D2E not found.

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Asset location: C:\PROGRAMAS\Steam\steamapps\common\Mansions of Madness/Mansions of Madness_Data
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG MoM Version Found: 1.3.3

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "C:\Users\RUBEN\Desktop\valkyrie-win-1.0.1\valkyrie_Data\content\D2E\ffg\import.ini".
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 1100 -> priority: 1 

Unloading 4 unused Assets to reduce memory usage. Loaded Objects now: 473.
Total: 0.375403 ms (FindLiveObjects: 0.029328 ms CreateObjectMapping: 0.019430 ms MarkObjects: 0.320045 ms  DeleteObjects: 0.005132 ms)

  Thread -> id: ccc -> priority: 1 
Unloading 2 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 527.
Total: 4.621051 ms (FindLiveObjects: 0.024562 ms CreateObjectMapping: 0.019796 ms MarkObjects: 4.560195 ms  DeleteObjects: 0.015397 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 528.
Total: 4.412087 ms (FindLiveObjects: 0.038493 ms CreateObjectMapping: 0.020529 ms MarkObjects: 4.347198 ms  DeleteObjects: 0.005499 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Warning: Unable to read file: C:\Users\RUBEN\AppData\Local\Temp\Valkyrie/TheFallofHouseLynch.valkyrie
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Material Font Material doesn't have _Stencil property
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)


Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 448.
Total: 4.346464 ms (FindLiveObjects: 0.023829 ms CreateObjectMapping: 0.019063 ms MarkObjects: 4.298073 ms  DeleteObjects: 0.005132 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 6 unused Assets to reduce memory usage. Loaded Objects now: 349.
Total: 4.123935 ms (FindLiveObjects: 0.031161 ms CreateObjectMapping: 0.019063 ms MarkObjects: 4.058680 ms  DeleteObjects: 0.014664 ms)

Failed to connect to raw.githubusercontent.com port 443: Bad access
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 346.
Total: 0.481718 ms (FindLiveObjects: 0.020529 ms CreateObjectMapping: 0.018696 ms MarkObjects: 0.416829 ms  DeleteObjects: 0.024929 ms)

**Comment by NPBruce** [comment] 2017-05-08 02:18
Issue 1:
Currently downloads only works if you have direct access to port 443 on a public server (raw.githubusercontent.com) without a proxy.  Valkyrie quits because I don't have good error handling here.  As a work around setting HTTPS_proxy environment variable to your proxy server should work.  I can't see a simple/nice way to just the the windows default proxy (which I assume is working).  Raised as #401.  If you aren't using a proxy and do have direct internet access let me know.

Issue 2:
Manually placing the valkyrie package should have worked.  Can you please try extracting the file (it is just a .zip file you can rename it) and try again?

**Comment by rubensemp** [comment] 2017-05-08 12:10
I'm not using a proxy. I've opened port 443 in the router but it still crashes.

I've downloaded a .valkyrie file from the URL that you told me, but when I rename it to .zip and I try to extract it says it's a corrupted file.

**Comment by NPBruce** [comment] 2017-05-08 12:15
Shouldn't have to change your router, that is for incoming connections, might want to close that again.

My only thought right now is there is a transparent proxy someone in your connection which is playing with things that it shouldn't.  I will leave this for now and see if anyone else has this problem or I can reproduce anything.

**Comment by rubensemp** [comment] 2017-05-08 12:32
OK, thanks for your responses!

**Comment by redwolf2** [comment] 2017-05-08 16:35
If NPBruce's suggestion is the problem, try it using a VPN. You can get a free trial account with 2 GB bandwidth at https://hide.me

**Comment by eorahil** [comment] 2017-05-08 16:41
The weird part of this is that if you download the scenario it's corrupted. This shouldn't happend.

if you go to this page 
https://github.com/NPBruce/valkyrie-store/tree/master/MoM
place your mouse cursor over TheFallofHouseLynch.valkyrie
right click and "Save target As..." should open you a download dialog and get the .valkyrie file
it's size should be about 210kb.
If you rename to zip it should be unpackable.
If you use a text editor to see it (the .valkyrie) the first 2 characters should be PK

**Comment by Zranz** [comment] 2017-05-08 16:57
"Save target as.." does not work, at least in Firefox. You need to access the file, then choose download button. Then, the downloaded file will have ~210 kB

**Comment by rubensemp** [comment] 2017-05-08 19:15
It's working! I downloaded the .valkyrie file in the way Zranz explained (and copied it in the path) and now the adventure appears in the START SCENARIO menu. Thanks for yours responses and advices! ;-)

**Comment by NPBruce** [comment] 2017-05-09 06:26
Closing this for now will look into it more if we get more issues coming in.

**Closed by NPBruce** 2017-05-09 06:26 UTC
