### ISSUE TITLE
Usefull feedback?

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#1254] opened 2020-02-17 18:57 UTC
### Description of Problem or Question

Some observations to the reviews made by players of the scenarios we make: 1) Some users simply don't comment on anything just vote the stage. 2) others simply close the app without voting 3) Then there are those that leave interesting comments that allow developers to improve the scenarios. In my case I paid close attention to the comments and made several changes, still, i have deleted the english translation due to negative comments on the traslation.

what are your opinions on feedback?

### Valkyrie Version
2.4.06

**Comment by scrubbless** [comment] 2020-02-17 20:02
I like the feedback even if it's just a score. Of course you get extreme cases but having a score next to scenarios proving that some are ver good only strengthens the credibility of Valkyrie.

**Comment by antontimmermans** [comment] 2020-02-18 14:44
The score is both useful and frustrating, especially if you see that your scenario typically scores between 7-9 and then someone just scores a 1 without any comment. You know that that is just some one trolling or undermining your scenario. On the long run, the impact of that 'trolling score' on the average scenario score is not so much.
That is why I think it is good to show a score of a new scenario only after it has reached a certain number of plays, so the score average is a better indicator. Alternatively, an algorithm calculating the score could also filter out outliers. 
The score is just a score, and only an indicator of what type of scenarios are more appreciated then others. As a scenario writer you can use this to your advantage and adjust your style, story or scenario quality. But don't expect you can please all.

The written feedback works basically the same. Reported bugs, misspellings or obvious flaws in the scenario are very useful to improve the scenario. 
Other comments can be very motivating or frustrating or even contradicting. Like : "too simple because clues where to abundant and obvious" vs "we guessed the solution because there where no clues".
Also here you have to take your own conclusion as a scenario writer. Leave the scenario "as-is" because it is "as intended" or adjust the scenario in line with the feedback.

Last weekend I played a SoA scenario and a HJ scenario in the ffg app. Both times the scenarios screwed up when it tried to tap into PoS resources. Unfortunately, the ffg app does not have the possibility for feedback, missing the chance for quick feedback and improvement. 
Luckily the Valkyrie app has the feedback option. And because of that, it helped me to improve my scenario (after getting over the frustration of some of the feedback ;-)  ). 

So, I consider the feedback option of Valkyrie a strength.

**Comment by scrubbless** [comment] 2020-02-18 15:07
Hiding scored until it hits say 10 plays might help prevent early bad scorings.

Another option we have is to purge all scores for a scenario. For example if a low scored scenario has a major overhaul I could purge the previous scores (I did this with Shadow Rune and Arkham Crimewaves platters).

**Comment by newusergettingnuts** [comment] 2020-02-18 16:43
scoring a one to a scenario that has to say an average of 5 to 8 or more means usually a flamer with no respect at all to the work of the developer.

**Comment by scrubbless** [comment] 2020-02-18 17:28
The ratings should be 1-5 really it creates less wild deviations on high and low scoring. We are scoring 1-10 and then halving it at present so have larger disparities.

**Comment by scrubbless** [comment] 2020-03-06 23:25
I'll close this, but feel free to continue the discussion while it's closed.

**Closed** 2020-03-06 23:25 UTC
