### ISSUE TITLE
Bug in Music and Audio Selector on Preview

### ISSUE THREAD

**Issue by AntonioFico** [NPBruce/valkyrie#1220] opened 2019-10-27 10:16 UTC
### Description of Problem or Question
Hi,

Excuseme but when you click on "Play" (button to the right of the file name) to listen different Audio during Audio and Music selection they dosen't stop also if you close the selector.

I think this is a bug

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by NPBruce** [comment] 2019-10-27 23:21
Closing as a duplicate of #1108

**Closed by NPBruce** 2019-10-27 23:21 UTC
