### ISSUE TITLE
Crash to desktop in-game

### ISSUE THREAD

**Issue by jlederer2** [NPBruce/valkyrie#1201] opened 2019-08-24 02:18 UTC
### Description of Problem or Question
Load save.  End investigator phase.  Go thru mythos phase and end that phase.  Game crashes to desktop just before monster would activate.
I noticed that the monster (Dimensional Shambler) shows 4 health in green box on upper right of main screen but has 12 health shown in upper left of screen if you try to attack it.

Had same issue in a previous run of this scenario at same point.

### Valkyrie Version
2.4.04

### Attach Save, Quest or Scenario
Log File:
[output_log.txt](https://github.com/NPBruce/valkyrie/files/3536762/output_log.txt)
Save:

[save3.zip](https://github.com/NPBruce/valkyrie/files/3536765/save3.zip)

**Comment by jlederer2** [comment] 2019-08-24 02:35
Here is save file from prior turn, in case this is useful.  If you end the turn, the Dim Shambler is spawned.
[save2.zip](https://github.com/NPBruce/valkyrie/files/3536775/save2.zip)

**Comment by scrubbless** [comment] 2019-08-24 21:26
Do you have HJ enabled in you content. Or as a required expansion  on the scenario?

**Comment by jlederer2** [comment] 2019-08-25 11:50
I have it enabled.  Scenario doesn’t require it but uses HJ if present.

Jim Lederer
248-482-3668

**Comment by NPBruce** [comment] 2019-08-26 00:08
Definately looks like Horific Shambler is broken, I will investigate (wasn't around for HJ).

**Comment by NPBruce** [comment] 2019-08-26 04:15
Under test in 2.4.05a

**Comment by NPBruce** [comment] 2019-08-26 04:16
https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F2.4%2Fv2.4.05a

**Comment by NPBruce** [comment] 2019-08-26 08:28
Outstanding questions:

I don't know where/how these shambler texts or how rifts work, or what {1} is:
MONSTER_DIMENSIONAL_SHAMBLER_00a,The creature rends reality apart in search of prey. Place a Rift in the {0}'s space.
MONSTER_DIMENSIONAL_SHAMBLER_00b,"The creature shambles forward, a tear in reality appearing in its path. Place a Rift in the {0}'s space. Then move the {0} to the farthest space of the {1}."
MONSTER_DIMENSIONAL_SHAMBLER_00c,The creature seeks prey however it must. Place a Rift in the {0}'s space. Then the {0} moves to {1}'s space.
MONSTER_DIMENSIONAL_SHAMBLER_00c_ALT,The creature seeks prey however it must. Place a Rift in the {0}'s space. Then the {0} moves to {1}'s space.

When a Hunting Deep one "moves up to 2 spaces to be in a space with as many investigators as possible", what does the cant move button say?

Dimensional shambler has this activation: "The {0} moves up to 2 spaces to be adjacent to the nearest investigator."
The normal language is :"The {0} moves up to 2 spaces toward the nearest investigator."
I don't understand the distinction, can someone helpe me understand why there is the special language case for just one activation?

**Comment by jlederer2** [comment] 2019-08-26 11:46
I tried the scenario starting from one of the save files, cycling through until a dimensional shambler was spawned.  Everything appears to work properly.
I can't answer your questions...perhaps the scenario author (Anton?) might know something, didn't see a contact email for him.

The rules for dimensional rifts say:

After an investigator in a space containing a rift performs an action other than the move action, if there is a rift in their space, they become Lost in Time and Space (a new condition).
- When an investigator forfeits an action in a space containing a rift, they become Lost in Time and Space.
As an action, an investigator may attempt to close a rift by testing their lore.  For each success, they may discard a rift from their space, or a space they move into later in the round.
- Rifts discarded by this effect do not cause an investigator to become Lost in Time and Space.
A rift cannot be placed in a space containing a rift.

**Comment by NPBruce** [comment] 2019-08-26 11:50
The questions relate to HJ in general rather than the scenario. Anyone who has played HJ, or is willing to play around the app should be able to work it out (I can't do it right now).

**Comment by jlederer2** [comment] 2019-08-26 12:07
Understood.  I played with the scenario in question for a while and never saw any of those messages for the dimensional shambler.  I also edited the scenario to spawn a hunting deep one and played with that for a while, never saw the message in question.

I thought perhaps Anton might have seen those messages while editing his scenario.

I'm suspicious that there is some other variable that needs to be set in order for the shambler to do any actions which would spawn rifts i.e. "RiftsEnabled".
I thought

**Comment by jlederer2** [comment] 2019-08-26 12:41
Thanks for the quick fix!

Jim Lederer
248-482-3668

**Comment by antontimmermans** [comment] 2019-08-27 20:12
> Outstanding questions:
> 
> I don't know where/how these shambler texts or how rifts work, or what {1} is:

A rift is a bit like a fire token. You can clean up the fire tokens with agility tests, rifts can be cleaned by lore tests in the same way. If an investigator takes any action other then cleaning the rift in a place containing a rift, he/she becomes lost in time and space (Which can actually be useful). The investigator receives a special condition card and is removed from the board. Only after successfully clearing the condition on the card, the investigator may return to the board.

With the HJ-train scenario I could reproduce the following:

> MONSTER_DIMENSIONAL_SHAMBLER_00a,The creature rends reality apart in search of prey. Place a Rift in the {0}'s space.

{0} is the Dimensional shambler:
![Shambler 4](https://user-images.githubusercontent.com/42072372/63797146-c2b35f00-c907-11e9-8f47-b96942a7244d.jpg)


> MONSTER_DIMENSIONAL_SHAMBLER_00b,"The creature shambles forward, a tear in reality appearing in its path. Place a Rift in the {0}'s space. Then move the {0} to the farthest space of the {1}."

{0} is the Dimensional shambler:
{1} is a (random reveiled) tile name
![Shambler 3](https://user-images.githubusercontent.com/42072372/63797332-2a69aa00-c908-11e9-87ca-ee900e0e618a.jpg)


> MONSTER_DIMENSIONAL_SHAMBLER_00c,The creature seeks prey however it must. Place a Rift in the {0}'s space. Then the {0} moves to {1}'s space.

{0} is the Dimensional shambler:
{1} is an investigator
![Shambler 6](https://user-images.githubusercontent.com/42072372/63797842-268a5780-c909-11e9-9faf-25874f67e0a4.jpg)


> MONSTER_DIMENSIONAL_SHAMBLER_00c_ALT,The creature seeks prey however it must. Place a Rift in the {0}'s space. Then the {0} moves to {1}'s space.

I guess this is the same as previous. So far, I have not encountered other types of text yet.


> 
> When a Hunting Deep one "moves up to 2 spaces to be in a space with as many investigators as possible", what does the cant move button say?
> 

I have tried to reproduce the message above in the boat scenario but was unable to replicate it. All messages where about a Hunting Deep One trying to hit the person in the (adjacent) space or moving towards them. The closest one matching your text I could find was:
![HDO2](https://user-images.githubusercontent.com/42072372/63804197-e9c55d00-c916-11e9-8d04-cfce83eadb7f.jpg)
With this message and ANY other message the result of selecting the"cannot move within range", was no follow-up action. The monsters turn ended.


> Dimensional shambler has this activation: "The {0} moves up to 2 spaces to be adjacent to the nearest investigator."
> The normal language is :"The {0} moves up to 2 spaces toward the nearest investigator."
> I don't understand the distinction, can someone helpe me understand why there is the special language case for just one activation?

My guess would be that moving 2 spaces towards an investigator might bring the shambler closer to an investigator, but not adjacent. If a Dimensional Shambler cannot move 2 space to be adjacent to an investigator, he might want to use his rift to 'jump to a tile or investigator.
Maybe a native English speaker has an alternative explanation

**Comment by NPBruce** [comment] 2019-08-28 00:41
Thanks for your help. Does it seems reasonable to leave the rift messages out and have it scenario specific?

> With this message and ANY other message the result of selecting the"cannot move within range"

This sounds like a bug, it doesn't have to do with range, should say "cannot move to be adjacent", but that text doesn't exist, so I will match the official version. Also likely that move moving 2 spaces after using it is a bug, but I will also match there as well.

**Comment by antontimmermans** [comment] 2019-08-28 07:03
> Thanks for your help. Does it seems reasonable to leave the rift messages out and have it scenario specific?

If you can play a scenario containing a Dimensional Shambler then you also have the HJ expansion. Which means you also have rifts.  I assume that a scenario writer would choose them in his/her scenario for this particular behavior. At least that was what did did with one of my scenarios. There are plenty other monsters to choose from that just move around 2 spaces and physically hit. The rifts make him special (and fun).

> 
> > With this message and ANY other message the result of selecting the"cannot move within range"
> 
> This sounds like a bug, it doesn't have to do with range, should say "cannot move to be adjacent", but that text doesn't exist, so I will match the official version. Also likely that move moving 2 spaces after using it is a bug, but I will also match there as well.

Sounds reasonable. fyi: The Hunting Deep One uses physical attacks, not ranged.

**Comment by scrubbless** [comment] 2019-08-28 07:13
> Thanks for your help. Does it seems reasonable to leave the rift messages out and have it scenario specific?

I agree with anton here, the creature is built around the rifts and since its tied to the expansion that has the rifts I'd leave it in. What's a Dimensional Rambler if it can ramble through dimensions!

**Comment by NPBruce** [comment] 2019-08-28 07:16
OK, if you are both suggesting it should do this somehow, how? When would this message come up?

**Comment by scrubbless** [comment] 2019-08-28 07:23
> Dimensional shambler has this activation: 

"The {0} moves up to 2 spaces to be adjacent to the nearest investigator."

The shambles may have abilities that are target an or all adjacent investigators. This will mean it tries to be next to but not in the same space as an Investigator. 

The normal language is :"The {0} moves up to 2 spaces toward the nearest investigator."
I don't understand the distinction, can someone helpe me understand why there is the special language case for just one activation?

Moving towards will put the shambler in the same space and therefore melee range if its target, which may not be intended for the creatures ability. Also having to move to melee is a penalty in a way.

**Comment by antontimmermans** [comment] 2019-08-28 08:15
> OK, if you are both suggesting it should do this somehow, how? When would this message come up?

If in the the Shambler is able to use it's attack when it is activated  (move 2 spaces to be adjacent and attack an investigator..., etc...), it will attack. 
When it is unable to attack it will display the rift messages:
MONSTER_DIMENSIONAL_SHAMBLER_00a
MONSTER_DIMENSIONAL_SHAMBLER_00b
MONSTER_DIMENSIONAL_SHAMBLER_00c
MONSTER_DIMENSIONAL_SHAMBLER_00c_ALT

**Comment by scrubbless** [comment] 2019-08-28 08:17
Sounds very similar to the ghost. If it cant attack it will teleport somewhere

**Comment by NPBruce** [comment] 2019-08-28 20:38
Ah OK typically it is if the creature cant move, rather than can't attack that this happens.

"The {0} moves up to 2 spaces toward the nearest investigator" can always happen (the normal activation), so this means you would always be moving the monster, then if it can't attack rifting it. Does this sound right?

**Comment by scrubbless** [comment] 2019-08-28 21:28
Yeh that sounds about right to me

**Comment by NPBruce** [comment] 2019-08-29 03:18
Released in 2.4.06

**Closed by NPBruce** 2019-08-29 03:18 UTC
Labels: MoM2E, bug, help wanted
