### ISSUE TITLE
valkyrie-windows-2.2.00b crashes while playing a scenario without the required content

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1065] opened 2019-02-14 03:14 UTC
I've found two problems in the valkyrie-windows-2.2.00b in the scenario 'Stress and Strain'.
~~I'm not sure if it's a general problem of just with the scenario.~~ It's a general problem. I've just tried to run 'A Little Night Music' scenario. Right after I clicked 'Continue' on the starting screen, the app crashed. 

First of all, the app crashes if you don't select the required content in the 'Select Content' menu for a scenario. 

Additionally, I've just found a strange behaviour on the course of events in the 'Stress and Strain' scenario. Read more further in 6.. 

Scenario:
1. Download the scenario. 
2. Make sure **you don't have** expansions required for the scenario selected in the 'Select Content' menu.
3. Start the scenario. The number of players doesn't matter.
4. Interact as follows: sight token on the right, sight token at the bottom, explore token at the bottom, attempt to break in. 
5. **If you pass the test** (you open the door): the game crashes instantaneously. _It's caused by the lack of a tile's or a monster's image._
6. **If you fail the test**: at first the token becomes unresponsive (click on it and check). If you go to the Mythos Phase 'funny' things starting to happen. In the beginning, click Continue. And now... As many times you clicked the unresponsive button, the number of times you will see the 'unresponsive button' event's text. After that, the game comes back to normal. I presume there is something wrong with the audio played after you fail. _The failure is caused by appearing of a monster which's image exists only in an expansion._ 
7. If you failed the test, you can go back to 5. and crash the app.

### Valkyrie Version
valkyrie-windows-2.2.00b

### Attach Save, Quest or Scenario
Log File for the Stress and Strain:
[output_log.txt](https://github.com/NPBruce/valkyrie/files/2863124/output_log.txt)
Log File for the A Little Night Music: 
[output_log.txt](https://github.com/NPBruce/valkyrie/files/2863155/output_log.txt)

**Comment by scrubbless** [comment] 2019-02-14 08:07
Stress and Strain requires MoM1eT and MoM1eM.

The explore token you mention is placing the MoM1e furnace tile.

Its crashing because you don't have mom1e or RN selected. It should not let you start the scenario. This is a major bug imo.

**Comment by chrismaliszewski** [comment] 2019-02-14 08:48
@scrubbless, I agree, it's **a major bug**. Especially since I start it from SE as a normal player would do. 

But the behaviour isn't expected - the app should not ever crash. I remember playing other scenarios to which I didn't have expansions without the app crashing in v2.15. 

The expected solution would be either:
A. As you said, not letting a user run a scenario at all. But I don't like the idea for a few reasons. 
1. If you don't allow a user to run a scenario, why would you allow to download them in the first place? Shouldn't the download option be disabled then too?
2. Since you allow a user to display scenarios in SE (I mean, if a user doesn't have 'Hide scenarios' filter selected), you should allow them to play it/check it just for fun. 
3. If we go with the idea, it'd be good if it was implemented in the SE instead of a scenario's splash screen so a user immediately sees that the scenario is not playable as it's now in the original MoM's app. **But**, I think simply disabling the play button is not enough as a user may think 'why can't I play this scenario?!' because there won't be enough info to say 'why'. In the original app, there is information 'why' such as 'Physical Product Required' but here there is no place for that.

B. Displaying extra information (i.e. message box) when a user wants to start a scenario that he/she doesn't have required expansions but if he/she wants to play it's possible and the app won't crash as it was before in v2.15.

**Comment by scrubbless** [comment] 2019-02-14 18:59
It's expected behaviour as in, that's how it has always been in Valkyrie.

If the app tries to place a tile from an expansion that is not in the library the app crashes. It's always done that.

It would be nice for it not to be how it operates and error message would be better, for example.

**Comment by chrismaliszewski** [comment] 2019-02-14 20:14
@scrubbless, **I'm sorry**, you're right about being unable to play a scenario without the required expansions in the previous versions. I had a false memory. I must have turned them on apparently before playing the scenario or I was playing it in the editor.

**Comment by scrubbless** [comment] 2019-02-15 08:47
I've noticed that 2.2 will show expansions in red if you don't have then. However it really should not allow you to play a scenario when the content is not selected.

**Comment by chrismaliszewski** [comment] 2019-02-15 09:17
Off-topic: Yeah, I've noticed that too. An expansion's icon changes to black if you have the expansion selected in the 'Select Content' menu. It's a nice feature which I really like! There is one more thing that would be nice which is described here https://github.com/NPBruce/valkyrie/issues/1061.

**Comment by chrismaliszewski** [comment] 2019-02-15 09:29
I have an idea:
![image](https://user-images.githubusercontent.com/7532602/52847186-63aea980-3170-11e9-8e48-a5ec92ec0024.png)

1. Creating a simple button that says something in between 'STOP' and 'you shall not pass' which does nothing but it being displayed. 
2. Add a clear indication what is wrong with the scenario or there is something wrong with it in any other way; i.e. in this instance display a 'Missing Expansions' label and all missing expansions' icons next to it (note: all other expansions which are active are displayed black in a line above). In the future the method could be used to indicate other problems, i.e. that a scenario file is currupted etc.
3. Change a font color of each scenario with a problem. I think the font colour should differ from the 2. label.

**Comment by scrubbless** [comment] 2019-02-15 09:51
I like this idea @chrismaliszewski

**Comment by BenRQ** [comment] 2019-02-15 10:30
There is no room for additional text there, it's already used by synopsys. I could add a text on the quest details screen though.

**Comment by chrismaliszewski** [comment] 2019-02-15 10:39
You're right. I forgot. 
So instead it could look like that:
![image](https://user-images.githubusercontent.com/7532602/52851313-a70e1580-317a-11e9-8c21-fda56cc79110.png)
I don't like the idea of clicking the 'Play' button to get to know that I can't play it and I need to go back. It should be clear from the very beginning.

**Comment by redwolf2** [comment] 2019-02-15 13:54
There is also this warning symbol: ⚠

**Comment by scrubbless** [comment] 2019-02-15 18:20
I just want to make sure the major issue in this thread isn't getting lost.

At present you can start a scenario even if you don't have the required content selected.

The rest is cosmetic.

**Comment by chrismaliszewski** [comment] 2019-02-15 22:23
@redwolf2, could you create the red button similar to the one you've already created here https://github.com/NPBruce/valkyrie/issues/1042 (https://github.com/NPBruce/valkyrie/files/2824450/play_button.zip)? 

An alert icon could be that one https://commons.wikimedia.org/wiki/File:Android_Emoji_26a0.svg.  
I think the hue shift which looks good is -116,3. 

I'm not sure how to do that with GIMP.

The icon could be used to in the proposed solution of the bug.

**Comment by BenRQ** [comment] 2019-02-16 15:58
I'm fine with your latest proposal @chrismaliszewski .

Regarding the picture I personally prefer the sign "no-entry" rather than "warning".
Warning means something is wrong, so it may be misleading.

**Comment by BenRQ** [comment] 2019-02-16 17:01
First try: 
- Red is probably too strong
- Title in red is maybe too much 
- Picture should be improved

![image](https://user-images.githubusercontent.com/40794717/52902700-be014600-3214-11e9-82d8-934ff5b5360a.png)

Please tell me what you think.

**Comment by scrubbless** [comment] 2019-02-16 17:37
Waiting for a red swirl with a white line in it ;)

**Comment by chrismaliszewski** [comment] 2019-02-16 18:52
I checked the title colour and I think black should be fine as the red-ish colour below stands out more because of that. If it's not enough, it could be easily changed later on.   

Text below is #af0806, instead of pure red.

I modified @redwolf2's project to PSD
[play_button.zip](https://github.com/NPBruce/valkyrie/files/2872290/play_button.zip)
and created a new button
![play_button](https://user-images.githubusercontent.com/7532602/52903884-02c6c480-3289-11e9-82e9-47102dcef5ee.png)
@scrubbless, it's centered 99.999% :).

So the current proposition is:
![image](https://user-images.githubusercontent.com/7532602/52903875-e2970580-3288-11e9-8f61-f1e57388f92f.png)

**Comment by redwolf2** [comment] 2019-02-16 19:11
All great, but maybe make the bar in the middle transparent.

**Comment by chrismaliszewski** [comment] 2019-02-16 19:18
I don't think it's a good idea but below is the transparent version
![stop_button](https://user-images.githubusercontent.com/7532602/52904112-2c351f80-328c-11e9-8275-dcb057ac06d9.png)
And here is a comparison:
![image](https://user-images.githubusercontent.com/7532602/52904131-7e764080-328c-11e9-9df1-34f2004b48e4.png)
I prefer a white strip version. Do you agree?

**Comment by scrubbless** [comment] 2019-02-16 19:30
Yeh its more true to purpose. The black (transparant) looks odd

**Comment by redwolf2** [comment] 2019-02-16 21:43
Alright, but then the other buttons should also have a white core.

![button_download](https://user-images.githubusercontent.com/4141621/52905558-2c0d3380-323c-11e9-948d-7534ad2541e8.png)
![button_play](https://user-images.githubusercontent.com/4141621/52905559-2ca5ca00-323c-11e9-834c-a4437822371b.png)
![button_refresh](https://user-images.githubusercontent.com/4141621/52905560-2ca5ca00-323c-11e9-88fe-14e44a5cf3bc.png)

**Comment by BenRQ** [comment] 2019-02-16 23:12
For the red text, it could be a bit darker maybe?
I like the no entry sign with white line.

![image](https://user-images.githubusercontent.com/40794717/52906257-506f0d00-3248-11e9-8e3f-e81bc13840bc.png)

I think the download and play button look better in black though, easier to read.
I don't think it would be a problem to keep them in black : see capture below.

![image](https://user-images.githubusercontent.com/40794717/52906274-a9d73c00-3248-11e9-96e0-9589d2c1abb8.png)

**Comment by BenRQ** [comment] 2019-02-16 23:17
Also I would need some translations for

`MISSING_EXPANSIONS,Missing expansions: `

**Comment by redwolf2** [comment] 2019-02-16 23:19
Ok, keep them black, otherwise constrast may be a problem from afar.

**Comment by BenRQ** [comment] 2019-02-16 23:39
OK I've committed this change. I will keep it open a while so you can share the text translation.

**Comment by chrismaliszewski** [comment] 2019-02-16 23:42
PL
MISSING_EXPANSIONS,Brakujące rozszerzenia:

**Comment by chrismaliszewski** [comment] 2019-02-16 23:46
> For the red text, it could be a bit darker maybe?
@BenRQ, have you tried the #af0806 red colour? It is a bit darker as shown here https://github.com/NPBruce/valkyrie/issues/1065#issuecomment-464371803.

**Comment by BenRQ** [comment] 2019-02-17 00:11
> @BenRQ, have you tried the #af0806 red colour? It is a bit darker as shown here [#1065 (comment)](https://github.com/NPBruce/valkyrie/issues/1065#issuecomment-464371803). And if it's still not enough, you could try making the font bold.

Yes the latest captures uses this colour.

**Comment by chrismaliszewski** [comment] 2019-02-17 00:20
Ok; didn't check that one. I like what you've shown in the last screenshot. 

Before showing previous propositions, I tried different colours and I like the one. I think going darker may not be a good idea but let others speak if they have other opinions.

**Comment by scrubbless** [comment] 2019-02-17 09:53
I assume the no entry button will not start the scenario now?

**Comment by BenRQ** [comment] 2019-02-17 14:57
Yes, button is deactivated.

**Comment by BenRQ** [comment] 2019-02-19 01:38
Commit Polish translation and closing.

**Closed by BenRQ** 2019-02-19 01:38 UTC
Labels: bug
