### ISSUE TITLE
Stress and Strain : French Translation

### ISSUE THREAD

**Issue by Indoy** [NPBruce/valkyrie#700] opened 2017-12-01 13:20 UTC
@scrubbless 
Hi,
Huge work you've done!
However, translation complete but as usual, after doing my tests IG i check some troubles or i have misunderstandings : 

What do you mean by : 
- fantic movement
- SpawnLab
- The doctor **tisks** as he pulls out his last set of bandages.

Bugs / questions : 
- EventZombieRiotEvade1_Tile15.text,The creature's are all around you blocking every path. You attempt to force your way past. Suffer 2 face down damage as they claw at your as you attempt to pass. If you suffer one or more damage or horror you are unable to make any progress, end your movement action.
(Seems a test of something is missing for Damage or Horror check)

- The horror check windows pops (in english) before action of monsters during myhtos phase.

- Test with these three heroes:
CarolynFern
AshcanPete
AkachiOnyele
One of them has a {0} value during this myhtos event:
({0} entend une étrange voix grave prononcer son nom ( ; 2). En cas de succès, {0} résiste à l'envie de tourner la tête ou de répondre à cette voix. En cas d'échec, il ne réfléchit pas et répond)

- EventNSLightsOutLightFailed_Tile8.text, darkness tokens are still on {c:TileNorthStreet_Tile8}, {c:TileStreetCorner_Tile17} and {c:TileBeach_Tile4} tiles, whereas it is said discard them (mistake? they should not imo)

- {c:TileNorthStreet_Tile8} sometimes "_" is missing

- {cQItemLeadPipe} ":" is missing

- Research token after mysterious man's death doesn't discard IG

- Small détail: if u choose to set the lab on fire BEFORE investigate the room, the text speak about a mass/creature (whereas you theorically have no infos about it)

- Bug: During my tests, i choose to set on fire the lab. The creature goes out from the room (is about 18 HP). Problem, on the next mythos phase during the horror step, a second Dunwich has poped with 44 HP. I guess it's impossible to have two of them at the same time.

I'll post the final translation file after your replies!
Best Regards and congratulations for the work done!

**Comment by scrubbless** [comment] 2017-12-01 15:54
> Hi,
> Huge work you've done!

Yeh I think I made it a bit too big, the first half of the game is a bit slow, and all the plot comes in at the end. That is what my playtests have uncovered, but I think it will break the game to try to re-write that part. So clocking it down to lessons learned for the next one :D

> fantic movement

I think I fixed that spelling mistake - it should say "frantic movement".  As in chaotic/desperate/wild movement.

> SpawnLab
> The doctor tisks as he pulls out his last set of bandages.

Tisk is when you click your tongue. Like when you find out the train is delayed, you make that "tsk" noise before letting out a sigh.

> Bugs / questions :
> 
> EventZombieRiotEvade1_Tile15.text,The creature's are all around you blocking every path. You attempt to force your way past. Suffer 2 face down damage as they claw at your as you attempt to pass. If you suffer one or more damage or horror you are unable to make any progress, end your movement action.
> (Seems a test of something is missing for Damage or Horror check)

Ahh I think I removed the horror from that, as early playtests were sending Investigators insane! I'll fix that and remove the "horror" part.

> The horror check windows pops (in english) before action of monsters during myhtos phase.
Yeh I noticed that last time I ran it, I was trying to replicate the way that the official app does it, but its not working as intended. I will remove it.

Bruce has put in an enhancement to enable these reminders in the following Issue anyway #683

> Test with these three heroes:
> CarolynFern
> AshcanPete
> AkachiOnyele
> One of them has a {0} value during this myhtos event:
> ({0} entend une étrange voix grave prononcer son nom ( ; 2). En cas de succès, {0} résiste à l'envie de tourner la tête ou de répondre à cette voix. En cas d'échec, il ne réfléchit pas et répond)

I think this is fixed in #678


> EventNSLightsOutLightFailed_Tile8.text, darkness tokens are still on {c:TileNorthStreet_Tile8}, {c:TileStreetCorner_Tile17} and {c:TileBeach_Tile4} tiles, whereas it is said discard them (mistake? they should not imo)

I'll check this out, I think if you fail to light the torches it should only place fire in one space, but not remove the darkness. Darkness should only be removed when you succeed the test. I'll check the whole event series though, thanks for highlighting.

> {c:TileNorthStreet_Tile8} sometimes "_" is missing
> {cQItemLeadPipe} ":" is missing

I'll check these, I think there are 8 different ways of getting that lead pipe and I decided to rename it to a "metal spike" in the dialog more recently! Haha.

> Research token after mysterious man's death doesn't discard IG

IG? I assume you mean that the token isn't removed after searching the item? Did you spawn a lot of monsters in your play-through haha. I played 2 player with a friend and because I didn't limit spawns we had 8 monsters on the board before we fled!

> Small détail: if u choose to set the lab on fire BEFORE investigate the room, the text speak about a mass/creature (whereas you theorically have no infos about it).

My friends highlighted this too, its on my list to fix.

> Bug: During my tests, i choose to set on fire the lab. The creature goes out from the room (is about 18 HP). Problem, on the next mythos phase during the horror step, a second Dunwich has poped with 44 HP. I guess it's impossible to have two of them at the same time.

Hmm thats got to be broken, i'll check the whole event sequence. Its quite complicated. I suspect that I forgot to set the "BigNastySpawned" variable when spawning the burnt version.


> I'll post the final translation file after your replies!
> Best Regards and congratulations for the work done!

Thank you very much for your swift translation.
Did you play the scenario, if so please feel free to drop any feedback, feelings, criticisms on my repo:
https://github.com/scrubbless/PublishedScenarios/issues

I will not be offended, if you didn't enjoy it. Or felt it was lacking something, please let me know!

**Comment by scrubbless** [comment] 2017-12-01 16:19
Ok here is a list of fixes:

> EventZombieRiotEvade1_Tile15.text,The creature's are all around you blocking every path. You attempt to force your way past. Suffer 2 face down damage as they claw at your as you attempt to pass. If you suffer one or more damage or horror you are unable to make any progress, end your movement action.
> (Seems a test of something is missing for Damage or Horror check)

New Dialog:
The creatures are all around you blocking every path. You attempt to force your way past. Suffer 2 face down damage ({agility} negates), as they attempt to claw you while you pass. If you suffer one or more damage you are unable to make any progress, end your movement action.

> 
> The horror check windows pops (in english) before action of monsters during myhtos phase.
> Yeh I noticed that last time I ran it, I was trying to replicate the way that the official app does it, but its not working as intended. I will remove it.

I have removed the reminder, its not needed.

> EventNSLightsOutLightFailed_Tile8.text, darkness tokens are still on {c:TileNorthStreet_Tile8}, {c:TileStreetCorner_Tile17} and {c:TileBeach_Tile4} tiles, whereas it is said discard them (mistake? they should not imo)

Removed the darkness tokens, on the failing to light event in North Street.

> 
> {c:TileNorthStreet_Tile8} sometimes "_" is missing
> {cQItemLeadPipe} ":" is missing

Ok i've had a hunt for these, I think I got them all!

> Research token after mysterious man's death doesn't discard IG
Fixed that, token will be removed now

> Small détail: if u choose to set the lab on fire BEFORE investigate the room, the text speak about a mass/creature (whereas you theorically have no infos about it).

I have pushed the "Investigate" option to the top, so players will be forced to take a peak before they can do anything else.

> Bug: During my tests, i choose to set on fire the lab. The creature goes out from the room (is about 18 HP). Problem, on the next mythos phase during the horror step, a second Dunwich has poped with 44 HP. I guess it's impossible to have two of them at the same time.

That is a big bug! Fixed now. I forgot to set the variable "BigNastySpawned" to say that the monster was out. So when the deadly mythos hit, is saw "BigNastySpawned = 0" and spawned it. Won't do that now!

I encourage feedback, however brutal. 

But thank you again for your translation!

**Comment by Indoy** [comment] 2017-12-01 18:07
@scrubbless 
fast replies thx!
Here's the file. Helas no i did not play your scenario yet.... but i had a great pleasure to translate it, so no doubt i will appreciate it IG (In Game)! 
I let you mention my contribution as a mark of approval =)
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1522479/Localization.French.txt)

**Comment by scrubbless** [comment] 2017-12-04 16:18
Thank you for your hard work @Indoy !

It has been published now, I have added a "special thanks" in the authors section.

**Comment by scrubbless** [comment] 2017-12-06 18:24
Feel free to close this issue

**Closed** 2017-12-06 18:40 UTC

**Comment by Indoy** [comment] 2018-02-07 11:44
@scrubbless 
Hi !
Surfing on BGG, i see you ve made some enhancement in your scenario. Don't hesitate ask for me to translate in french some potentialy news lines if needed !
Regards
