### ISSUE TITLE
Ask user for file path if not found.

### ISSUE THREAD

**Issue by beppe9000** [NPBruce/valkyrie#990] opened 2018-12-20 22:19 UTC
The user should be asked to provide a path if none are found because of unusual locations.
In my case SteamCMD (official steam CLI client) has the 'steamapps' next to the executable.

The easy fix is to get the path from the user with the standard folder selection dialog (windows) [here](https://github.com/NPBruce/valkyrie/blob/2645a5594461fcf9c564bf5403335435b010bb36/unity/Assets/Scripts/UI/Screens/GameSelectionScreen.cs#L160).

**Comment by BenRQ** [comment] 2018-12-20 22:51
Hi @beppe9000 

This is a duplicate of #656 which is fixed.
There is even a known issue on this fix, that I need to work on : #984

Feature will be available in next release 2.2.

If this is blocking for you, you can try a technical version of 2.2 with no guarantee though :)
This would help us fix issue before release if you spot some issues.

And for the record, fixing this was not easy :)

**Closed by BenRQ** 2018-12-20 22:51 UTC

**Comment by BenRQ** [comment] 2018-12-20 23:34
A simple fix while you and probably other are waiting for the new release : 

Create a file valkyrie.reg with this content:

`
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 478980]
"InstallLocation"="C:\\Program Files (x86)\\Steam\\steamapps\\common\\Mansions of Madness"
`

- edit path if required
- double click reg file
- restart valkyrie

**Comment by beppe9000** [comment] 2018-12-20 23:51
That' a fine workaroudn thanks!

**Comment by beppe9000** [comment] 2018-12-21 00:35
Ok I tried Valkyrie and it's awesome. I didn't expect translated content in italian... Wow ! 👍
I suppose the official scenarios can't be played in Valkyrie? I can live with that.

Just one thing bothers me (also in the official app): being unable to hit 'continue' by pressing enter or space key

**Comment by redwolf2** [comment] 2018-12-27 10:40
Yes, there is no option to play the official scenarios using the valkyrie.

I opened an issue for the "continue on enter and space" idea.

**Comment by beppe9000** [comment] 2018-12-27 14:55
Nice!
