### ISSUE TITLE
Wrong tokens in scenario

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#232] opened 2017-04-10 22:23 UTC
A few days ago the House Lynch scenario changed its icons and where there was the red exploration tokens now there are the blue admiration ones. I downloaded again the scenario but nothing fixed. These new characters tokens should have shifted the other icons in the same image?
![2017-04-11](https://cloud.githubusercontent.com/assets/15666794/24884911/0ad55766-1e4c-11e7-906e-e02a39dbfb7b.png)

**Comment by Hobbeslionheart** [comment] 2017-04-11 00:39
I have not had this problem in the editor or gameplay.

**Comment by NPBruce** [comment] 2017-04-11 00:41
Has a new version of MoM come out?

**Comment by NPBruce** [comment] 2017-04-11 09:38
Can you please upload a log? What version of MoM do you have?

**Comment by eorahil** [comment] 2017-04-11 11:05
Im using MoM 1.3.3 but the problem is on my merged quest translation branch so the problem could be mine. I Thought it was a global problem but if you don't have it, it could be my fault.
Lets pause this as soon as I finish translation quests.

**Comment by eorahil** [comment] 2017-04-17 20:53
Its fixed now. Don't know exactly the reasons but now it works perfectly. Can be closed

**Closed** 2017-04-17 20:56 UTC
