### ISSUE TITLE
Descent campaign problem after calling 11th nested quest

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#809] opened 2018-04-26 23:35 UTC
### Description of Problem or Question
There seems to be a problem with Descent 2 campaigns that leads to a lockup of Valkyrie after calling the 11th nested quest via event1 entries. 

All quests work fine by themselves, but as soon as one of the quests is called as the 11th nested quest Valkyrie does not open the quest and no longer reacts to user input (for example menu options). 

Can this problem be solved somehow? Otherwise it will be pretty much impossible to create complex campaigns.

### Valkyrie Version
2.0

**Comment by NPBruce** [comment] 2018-04-27 00:32
11th is oddly specific.  Quests are not 'nested' at all, the only thing that caries over is the variables. Can you attach a campaign that recreates this problem?  I will investigate here, but there might be something specific in your quests which exposes the problem.

**Comment by DelphiDie** [comment] 2018-04-27 07:33
Hello Bruce,

thanks for your support. I will attach a campaign file.

[The Shadow Rune.zip](https://github.com/NPBruce/valkyrie/files/1954142/The.Shadow.Rune.zip)

A few notes:

The campaign is structured in this way:

Introduction Quest (1 Quest, just the launcher)
First Blood (1 Quest, can be skipped)
Campaign Phase (1 Quest, is called multiple times)
A Fat Goblin (2 Encounters but only 1 quest)
Campaign Phase (1 Quest)
The Cardinals Plight (1 Encounter, 1 quest)
Campaign Phase (1 Quest)
Death on the Wing (2 Encounters, 2 quests)
Campaign Phase (1 Quest)
The Masquerade Ball (2 Encounters, 2 quests)
Campaign Phase (1 Quest)
The Shadow Vault (1 Encounter, 1 Quest)

After 3 of the 4 quests "A Fat Goblin", "The Masquerade Ball", "Death on the Wing" and "The Cardinals Plight" are played, the campaign phase will offer either "The Shadow Vault" or "The Overlord revealed" (which is not yet implemented.

If you run both quests that contain 2 quest files (The Masquerade Ball and Death on the Wing), then the campaign will stall after finishing one of the other 2 quests (A Fat Goblin or The Cardinals Plight) when the campaign phase would be called.

If you run both quests that contain 1 quest file (A Fat Goblin and The Cardinals Plight), then the campaign will stall after the travel phase that follows after playing either of the other quests (The Masquerade Ball or Death on the Wing). Note that this can currently only be reproduced by winning at least 2 of the 3 quests, since you only get access to the Quest "The Shadow Vault" in this case.

I hope this description will suffice.

**Comment by DelphiDie** [comment] 2018-04-29 12:27
Just adding a newer version of the campaign file.

[The Shadow Rune.zip](https://github.com/NPBruce/valkyrie/files/1958714/The.Shadow.Rune.zip)

**Comment by NPBruce** [comment] 2018-04-30 03:06
I think the problem is the path not clearing.  For example you start with:

c:\users\name\AppData\Local\Temp\Valkyrie\The Shadow Rune\quest.ini
Then:
c:\users\name\AppData\Local\Temp\Valkyrie\The Shadow Rune\01_FirstBlood\quest.ini
Then:
c:\users\name\AppData\Local\Temp\Valkyrie\The Shadow Rune\01_FirstBlood\..\CampaignPhase\quest.ini
Then:
c:\users\name\AppData\Local\Temp\Valkyrie\The Shadow Rune\01_FirstBlood\..\CampaignPhase\..\02_AFatGoblin\quest.ini

Eventually the string will be too long and fail.  This will depend on where the quests are run from, the user name, the operating system and if the quests are packaged.

Fix is to ensure path is recreated on load. Can be worked around by manually editing save file.

**Comment by DelphiDie** [comment] 2018-04-30 07:48
Hello Bruce, thanks for your analysis. As a quick workaround I will shorten the names in the folder structure and start to convert everything into 1 encounter quests.

**Comment by NPBruce** [comment] 2018-04-30 09:09
I will certainly fix it, scheduled for 2,1.

**Comment by DelphiDie** [comment] 2018-09-04 09:01
Due to the new path system the problem should be fixed. Thanks a lot.

**Comment by redwolf2** [comment] 2018-09-05 14:41
Reopen, because it is fixed in Brynhildr, but not in Valkyrie. I created the label "Brynhildr" to track, what is covered by it.

**Comment by BenRQ** [comment] 2018-09-15 22:03
@redwolf2, I think this one is missing the Brynhildr tag

**Closed** 2018-10-08 00:13 UTC
Labels: Brynhildr, D2E, bug
