### ISSUE TITLE
Stuck in a fat Goblin

### ISSUE THREAD

**Issue by vogella** [NPBruce/valkyrie#1174] opened 2019-07-05 11:35 UTC
### Description of Problem or Question

We are trying to play "A shadow rune" and are stuck in "A fat Goblin". We killed Split but are unable to leave the level. I would guess that the level got confused as we still had a normal Goblin alive while killing Spit.

Any suggestion how to continue? Or do we have to start over?

### Valkyrie Version
Latest

### Attach Save, Quest or Scenario
We are using the Android App. How can I attach log from Android?

**Comment by DelphiDie** [comment] 2019-07-05 14:50
Hello Vogella,

I'm very sorry to hear that you had a problem. I just tested the quest itself, and it worked fine for me, even if there are Goblins alive when Splig is defeated.

My suspicion is, that this is related to #1170 and hence #842 

Could it be the case, that you started the quest, at some point saved the game, quit Valkyrie, and resumed the quest at a later time?

I was able to reproduce the error following these steps.

Unfortunately there is absolutely nothing I can do about this, as this seems to be a problem with the save / load system of Valkyrie itself. Sadly at the moment there seems to be no one around who could fix this :(

I'm currently considering to take the campaign offline, as this seems to lead to a lot of frustrating user experiences. You can't really play a campaign without a working save / load system after all.

Once again, I'm very sorry this problem is affecting you. It would be great to hear back from you.

**Comment by vogella** [comment] 2019-07-05 15:27
@DelphiDie indeed we did saved, quit and resumed later. Do you know if there is a way to remove the second ini file via the file system.

I would not recommend to take the campaign offline, it is really cool. We just need something to fix the issue. ;-) Is the app still under development?

**Comment by vogella** [comment] 2019-07-05 15:30
@DelphiDie scanning through #842 it looks like there is another app called Brynhildr. Do you know any details about it?

**Comment by DelphiDie** [comment] 2019-07-06 10:53
Hello Vogella,
Brynhildr was an experimental Valkyrie version which was created by @BenRQ 
It was a first attempt to fix the save / load bug years ago, and at the time it was successful.

At a later point Brynhildr was merged back in the original Valkyrie release, so it is severly outdated as of today.

Regarding app development I'm unsure if anybody is still working on Valkyrie actively at the moment.

**Comment by vogella** [comment] 2019-07-06 11:12
Hello DelphiDie,

Thanks for the response. Sorry to hear that development is not active
anymore.

I really enjoyed your levels, the road to legend levels seem much larger
and less creative compared to your scenario.

Best regards, Lars

DelphiDie <notifications@github.com> schrieb am Sa., 6. Juli 2019, 12:53:

**Comment by NPBruce** [comment] 2019-08-08 09:27
I am closing this is a duplicate of #842

**Closed by NPBruce** 2019-08-08 09:27 UTC
