### ISSUE TITLE
Can not open on macOS 10.15 

### ISSUE THREAD

**Issue by tghggns** [NPBruce/valkyrie#1214] opened 2019-10-11 03:38 UTC
### Description of Problem or Question
When opening Valkyrie app on macOS 10.15 Catalina, error is displayed

### Valkyrie Version
2.4.06

<img width="417" alt="Screen Shot 2019-10-11 at 4 35 56 PM" src="https://user-images.githubusercontent.com/56422494/66622779-87fe4f80-ec45-11e9-8ea2-1e9b2d31c77b.png">

**Comment by alfasnip** [comment] 2019-10-14 16:11
the same problem...  :( how I can solve it?

**Comment by jnierodzik** [comment] 2019-10-14 20:37
This sounds like the binary is not executable.  Assuming you have installed Valkyrie into the standard Applications folder run the following command from the terminal

`chmod +x /Applications/Valkyrie.app/Contents/MacOS/Valkyrie`

**Comment by ChrisChinchilla** [comment] 2019-10-15 01:35
I'm assuming this is because the binary is 32-bit?

**Comment by jnierodzik** [comment] 2019-10-15 01:47
> I'm assuming this is because the binary is 32-bit?

The binary is 64-bit per the OS' application profiler.  I was thinking an issue with the build settings in Unity, but I'm honestly not too familiar with those.

**Comment by ChrisChinchilla** [comment] 2019-10-15 02:33
Actually I found that with a few applications that weren't working under Catalina, re-downloading them typically fixed thew issue. I guess they were applications without in-built update mechanisms or something… So I can now confirm Valkyrie is working for me.

**Comment by NPBruce** [comment] 2019-10-15 03:01
The binary is universal (includes 32 and 64 bit). As a non-macos user this issue is a bit beyond me.

**Comment by jnierodzik** [comment] 2019-10-15 03:13
@NPBruce

How are you creating the zip file? Most windows archive tools don’t honor the proper file permissions inside the app bundle.  

Your build is probably fine, but zipping it on Windows for upload is what’s most likely breaking it.

**Comment by NPBruce** [comment] 2019-10-15 03:15
Yeah zip doesn't support unix permissions at all. It is currently using 7Zip. I'm happy to change to a tarball (like linux) or whatever else works better? I feel like zip was the advice I was given at the time.

**Comment by jnierodzik** [comment] 2019-10-15 03:19
DMG is the preferred format, but don’t believe you can do that on PC without additional software so tarball would be the preferred alternative.

I can also help out by creating DMGs if you would like.

**Comment by alfasnip** [comment] 2019-10-22 15:58
When i used Chrom - download successful but still can't open and intcstall at Catalina. I would like to ask for solution or info how i can install Valkyrie (Catalina). Thx :)

**Comment by alfasnip** [comment] 2019-10-29 09:40
Did anyone could solve this problem....? :(

**Comment by redwolf2** [comment] 2019-10-29 21:45
@alfasnip Did you follow the installation instructions? https://github.com/NPBruce/valkyrie/wiki

**Comment by ArkhamNative** [comment] 2019-11-18 15:25
Chiming in to say this is still an issue (no Valkyrie updates since first post). Downloaded latest version (as above, 2.4.06) and got the "can't be opened" message. Solved by using the suggestion above: use the Mac's Terminal utility and the given command-line "chmod" command to fix the permissions of the Valkyrie executable (contained inside the Valkyrie app) (after moving the downloaded app to the Mac's Application folder).

And as usual after install/update: Ctrl-clicked (or right-click) on the Valkyrie app and chose "Open" from the pop-up menu

Also clicked "Deny" to a dialog by Mac OS X 10.15 ("Catalina") asking to allow Valkyrie to accept keystrokes from any application. Apparently this is a Unity issue and was fixed in a more recent version, 2018.4 LTS. (I'm just repeating a googled response.)

**Comment by alfasnip** [comment] 2019-11-18 16:33
OK, I try Ctrl+click and open -> still don't work
I don't know what I should do with "chmod" command. I download one more time Valkyrie for os. I have it at downloaded files. Still can't open (even with ctrl). I try to put this file to app folder - still don't work. :(

**Comment by ArkhamNative** [comment] 2019-11-19 20:50
Step by step: After you download the Valkyrie app, move it to the Applications folder. (The same folder as Mail, Safari, etc.) 
Then start up Terminal. (It is in the Utilities folder of the Applications folder). In the Terminal window you type (or copy & paste):
  `chmod +x /Applications/Valkyrie.app/Contents/MacOS/Valkyrie`
Then hit hit enter. It won't display confirmation if it succeeds. That tells the Mac to mark the program file within the Valkyrie app as executable. (For some reason the program file didn't get marked that way in this version. It did in previous versions.)
If it succeeds, you will be able to ctrl-click + open the Valkyrie app and get the security message (instead of the "can't be opened" message). Click Open.
Once you have done all this, you can just double-click the Valkyrie app like normal to open it, until you reinstall Valkyrie or install another version.

**Comment by alfasnip** [comment] 2019-11-20 19:09
ArkhamNative@ I would like to thank you very much for help. Your solution solved my problem :)

**Comment by redwolf2** [comment] 2019-11-26 19:19
@ArkhamNative @alfasnip 
I added your solution to the installation instructions.

**Comment by eimerich** [comment] 2020-04-18 19:50
Fantastic: did the procedure, now fully operative! Thanks!

**Comment by mayjak** [comment] 2020-11-16 10:48
Reopening this. I can confirm changing to tar.gz archive after build is working fine on macOS Catalina. I'll update the build script in 2.4.11/2.5.

**Comment by mayjak** [comment] 2020-11-16 11:10
This  should be now fixed in the prerelease build of 2.4.11 by moving to .tar.gz format. At least it worked for me on my mac.

**Closed** 2020-11-25 11:34 UTC
