### ISSUE TITLE
A glimpse of the past - French translation

### ISSUE THREAD

**Issue by mponsot** [NPBruce/valkyrie#1303] opened 2020-05-29 12:34 UTC
Hi there,

I just finished a french translation for "A glimpse of the past" scenario.

I went into the scenario's git but there's no issues page to upload the file there so here it is :

[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/4701785/Localization.French.txt)

Thanks !

**Comment by scrubbless** [comment] 2020-06-04 08:50
Hi @slycozzolino

I believe this is for you

**Comment by slycozzolino** [comment] 2020-06-12 20:04
Sorry. Missed this.
Adding now.

**Comment by slycozzolino** [comment] 2020-06-12 20:15
I have made the update. Please note that this will not effect the images. If you want to translate those as well just add them to this ticket and I can set it up.

**Comment by BenRQ** [comment] 2020-09-21 23:10
![image](https://user-images.githubusercontent.com/40794717/93830064-7738c500-fc6f-11ea-9de6-e98215de1358.png)

Hi @slycozzolino , is there a particular attention to the wording (like a clue)?
Or can I translate so it sounds good in French?

AU NOM DU PERE,
ET DU FILS,
ET DU SAINT
FANTOME, AMEN.

![image](https://user-images.githubusercontent.com/40794717/93830262-01812900-fc70-11ea-9119-eab5b1fc7bf2.png)

I'm not sure if this one means "please return the paper":   "Merci de me ramener pour acheter mes produits"
or "please come back".  "Merci de revenir pour acheter mes produits"

**Comment by slycozzolino** [comment] 2020-09-21 23:20
Your translation will work for the first picture.
For the bottom one it will not. 

***SPOILER***
The capital letters represent the first letter of the color thus telling the order. 
If you want to do a translated text for this you can change it completely, but you need to leave the order Purple Red, Blue, Green.
Below is an example of how you could do it but the remainder of the sentence doesn't have a B or G so you will need to alter it.
"merci de me ramener PouR acheter mes produits"
The meaning of the text isn't all that important but it would be good if it related to a shop/selling goods purely for story telling purposes.

**Comment by BenRQ** [comment] 2020-09-26 13:10
OK please note the words for colors are different in French though.

Purple Red, Blue, Green
Violet Rouge Bleu Vert

This makes it a bit harder as they are two 'V' though.

"Véritablement Ravi de Bien Vous recevoir."

Which means "Really happy off welcoming you".
Does sound a bit weird though, but I think it's acceptable !

**Comment by slycozzolino** [comment] 2020-10-08 00:18
I wouldn't force the translation to make it work. It is possible to have a new puzzle just for the French translation. I'm open to ideas. I'll see if I can think of another one that language independent.

**Comment by scrubbless** [comment] 2020-10-08 09:36
The issue is that there is not variable to denote language that I have seen. 

If I could detect language it would make Escape easier to translate too as there are several word puzzles.

**Comment by slycozzolino** [comment] 2020-10-09 03:53
As long as the combination stays the same for the alternate image it will work. If you are talking about a new pattern just for French, then I agree there is not way to do that. Not that I know of.

**Comment by BenRQ** [comment] 2020-10-24 16:30
@slycozzolino if you decide to change this puzzle, I'd by happy to translate this shopping list :)

**Comment by slycozzolino** [comment] 2020-11-02 15:28
Well I don't want to change the puzzle for the English version. The text in reality doesn't matter so long as the combination is the same. If you think the one I purposed above will work lets add it. If I can get a translation of the shopping list I can make an image for the French translation. I will still need updates to the Localization file.

**Comment by vidimus** [comment] 2023-08-31 08:25
@scrubbless or @antontimmermans , could you close this issue? It was solved.

**Closed** 2024-01-15 09:51 UTC
