### ISSUE TITLE
[Bug] Incorrect Player Count Recorded in End Game Log (Book a Room for Murder)

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1358] opened 2020-09-20 15:23 UTC
I got a bad review on Book A Room for Murder, claiming that the game was too hard.  I looked at the log descriptions, and I found is:  **$%morale=2;#HeroDanielaReyes=1;#HeroFatherMateo=1;#heroes=5**
It appears that even though their were only two investigators, the game treated them as if there were 5 of them.  That affects the difficulty in the programming of the scenario, which might explain their complaint.

Book a Room for Murder

I'm not sure how to reproduce this error.

2.4.09

**Comment by NicolaZee** [comment] 2020-09-21 07:26
I noticed this and it is effecting several scenarios.
I'm wandering if maybe this is caused by rating a scenario in Test Mode.
Even if not, it would still be worthwhile to disable the submit button of the review screen in Test Mode.
Folks should not be submitting reviews while testing.

**Comment by NicolaZee** [comment] 2020-09-21 08:33
This is a major bug.
Disturbance At The Docks has had a number of bad ratings including 1 out of 10 because the number of heroes has been set to 5 while the number of actual investigators is much less.
I've tried to replicate by running Disturbance At The Docks in test mode but it does not seem to happen.
I've no idea why it seems to occur more in some scenarios than others.
Maybe these are just the scenarios which are getting played more and if there is no issue players don't bother to submit a review?

**Comment by BenRQ** [comment] 2020-09-21 19:58
That's indeed a bug, in the loading of savegames.

It's happening when the game is being loaded back (after a crash or after closing Valkyrie for example).
It's not happening when doing a full session without leaving the game session.

I have a quick fix available for this one.

**Comment by BenRQ** [comment] 2020-09-21 22:12
Will be fixed in 2.4.10

**Closed by BenRQ** 2020-09-21 22:12 UTC
Labels: bug
