### ISSUE TITLE
Unable to find Mansions of Madness Android 12

### ISSUE THREAD

**Issue by andybloke** [NPBruce/valkyrie#1611] opened 2023-03-13 12:50 UTC
### Description of Problem or Question
Installed MoM and Valkyrie. Opened MoM and allowed assets to load. Added File and Install permissions to Valkyrie. Opened Valkyrie, it reports that MoM cannot be found. Reinstalled Valkyrie, problem persists.

Samsung Tab S6 Lite  running Android 12 

### Valkyrie Version
2.5.8

**Comment by vidimus** [comment] 2023-03-13 19:58
Hello, @andybloke 
The problem is not Valkyrie but the official app. Try this workaround downgrading the official MoM app.
https://github.com/NPBruce/valkyrie/issues/1605

**Comment by Quantumrunner** [comment] 2023-03-16 10:17
This seems to be the same issue as in #1610. Seems like the latest Mansions of Madness update broke the import.

**Comment by andybloke** [comment] 2023-03-17 08:44
> This seems to be the same issue as in #1610. Seems like the latest Mansions of Madness update broke the import.

Which is the last known working version of MoM?

**Comment by andybloke** [comment] 2023-03-17 09:25
I'm working my way down versions. Can confirm 1.9.2, 1.9.1 and 1.9.0 have the same problem. 1.8.8 does indeed work

**Comment by Quantumrunner** [comment] 2023-11-14 19:19
Closed. Issue has been fixed in Release https://github.com/NPBruce/valkyrie/releases/tag/release%2F2.6%2F2.6.0a.

**Closed by Quantumrunner** 2023-11-14 19:19 UTC
