### ISSUE TITLE
[Bug] Quest Menu is unavailable

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1543] opened 2022-01-06 11:55 UTC
### Describe the bug

I am working on a scenario and have noticed that in the latest version the "Quest" tab in the components menu is blocked out, id normally use this to get back to the main page of the scenario to edit expansions, etc.

![image](https://user-images.githubusercontent.com/32058089/148379373-f1c8d597-e070-4683-82b5-7d5ba22dac88.png)

### Valkyrie Version
2.5.6 - Windows

**Comment by Hobbeslionheart** [comment] 2022-04-06 00:18
This has been broken since 2.5.2 which was a significant update. I will have to troubleshoot to figure out why.

**Comment by mayjak** [comment] 2022-04-10 21:01
As @Hobbeslionheart mentioned in https://discord.com/channels/473584815166455808/473586525477666826/962145592455352340
The cause is that the Quest editor item does not have a "Source". We should add that. QuestEditorData.cs:116

**Comment by antontimmermans** [comment] 2022-07-27 12:57
tested on 2.5.7b: Looks OK

**Comment by mayjak** [comment] 2022-07-29 10:08
Fixed in 2.5.7

**Closed** 2022-07-29 10:08 UTC
Labels: bug
