### ISSUE TITLE
Heroes/round count not set after savegame

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1053] opened 2019-02-06 20:43 UTC
### Description of Problem or Question

Issue remarked by "Tantum" on discord:

> Looks like the Shadow Rune campaign is having save problems again version 2.2.20190204. I can not start a new quest after loading a savegame.
> 
> You should be able to reproduce this error:
> 
> 1. Start a new campaign.
> 2. Skip the first quest.
> 3. Start a new quest and lose it (e.g. by dying to often).
> 4. Try to go to town.

![grafik](https://user-images.githubusercontent.com/4141621/52372275-0a4fc780-2a58-11e9-85a7-a0aa958fbbe7.png)

### Valkyrie Version
2.2.20190204

**Comment by MrTantum** [comment] 2019-02-07 14:11
I did not post this in Github because I'm not sure if this is a Valkyrie problem or a bug caused by the campaign structure.

I missed the save / load steps in the list:

1. Start a new campaign.
2. Skip the first quest.
3. Start a new quest and lose it (e.g. by dying to often).
**4. Save the game. Load the game**
6. Try to go to town.

**Comment by redwolf2** [comment] 2019-02-07 14:19
No problem, we can always close it and it might keep the next one from opening an issue, then they find the solution in the closed issues.

**Comment by BenRQ** [comment] 2019-02-08 00:14
@MrTantum can you please confirm if the same exact procedure is working in version 2.1.5 ?
This would confirm for sure that this is a bug.

**Comment by MrTantum** [comment] 2019-02-08 16:17
No I can not reproduce the error in 2.1.5.

I created a new game and followed the steps and it works:

![grafik](https://user-images.githubusercontent.com/31658807/52490553-4a808880-2bc5-11e9-8735-9fe48a50eb1a.png)

Furthermore when loading the same save state I have created for 2.1.5 did not work again in 2.2.3.

**Comment by BenRQ** [comment] 2019-02-10 22:15
I was not able to reproduce.
Here is what I did : 

* Start a new campaign.
* Skip the first quest.
* Start a new quest and lose it (e.g. by dying to often).
* Save the game in quest. Load the game   <= did you save in the quest or in the map screen ? I tried both.
* Go to town. Enter shop /LEave shop
* Start a quest 

Everything is working so far.

Can you please:
- confirm the OS you are running ? (android/windows/mac/linux)
- describe in more details what you are doing at each step ?

**Comment by MrTantum** [comment] 2019-02-11 19:29
@BenRQ I send you some screenshots in discord.

OS is Windows but I can reproduce the bug on android to.

**Comment by redwolf2** [comment] 2019-02-11 20:25
You can add images by copy & pasting to the comment window.

**Comment by BenRQ** [comment] 2019-02-11 22:55
I've been able to reproduce the problem with @MrTantum info.

Additional steps information:

Quest should be "Cardinal plight".
Save while in town.
After reloading, the continue button disappear when trying to enter town.

**Comment by BenRQ** [comment] 2019-02-11 23:29
For your information, you can debug tests by adding this in the config.ini file.
[Debug]
tests=1

This will show test result for each event in the logs.

In our case, the test heroes==4 and fame<4 is failing because heroes == 0

I'm checking why this is happing.

**Comment by BenRQ** [comment] 2019-02-12 00:53
I found a bug which has been here for quite a while.
Vars are saved by their name, in the savegame, but some vars name are starting with # which is a comment in the .ini format .
So they were ignored.

For example in our case : 
#round=1
#HeroGrisbantheThirsty=1
#HeroLeoricoftheBook=1
#HeroAshrian=1
#HeroTombleBurrowell=1
#heroes=4

All those vars where not loaded from savegame.

In 2.1.5 it was probably working because hero count was updated in another way.
I've fixed it for 2.2.

Also I discovered that all vars with value 0 are not saved.
For me this is a problem, you may want to save a var with value 0.
I can change that of course.

@scrubbless @redwolf2 would you think I should fix this last point regarding variables with value equals to 0 not being saved ?

**Comment by NPBruce** [comment] 2019-02-12 01:05
All variables are 0 by default, which is why they aren't added. A variable set to 0 is the same as one never set.

**Comment by BenRQ** [comment] 2019-02-12 01:24
Does it mean that if you check if a non existing var == 0, it will always return true ?

**Comment by NPBruce** [comment] 2019-02-12 01:37
Yes. There is no such thing as an uninitialised or 'non existing' variable, there are no definitions. Everything is 0 until set otherwise.

**Comment by BenRQ** [comment] 2019-02-12 01:48
OK thanks for clearing that up.
This issue is now fixed.

**Closed by BenRQ** 2019-02-12 01:48 UTC
Labels: bug
