### ISSUE TITLE
stuck in city on load game

### ISSUE THREAD

**Issue by 0gravitas** [NPBruce/valkyrie#1170] opened 2019-06-09 09:40 UTC
### Description of Problem or Question
If I save the game while in the city/shop screen, after loading the save shop UI is gone and I am unable to proceed with the campaign.

Steps to reproduce:

1. Start Shadow Rune campaign
2. Finish first quest
3. Enter city
4. Save game
5. Load game

### Valkyrie Version
2.3.04

### Attach Save, Quest or Scenario
Log File:
[output_log.txt](https://github.com/NPBruce/valkyrie/files/3269390/output_log.txt)
Saves:
[save2.zip](https://github.com/NPBruce/valkyrie/files/3269393/save2.zip)

**Comment by MrTantum** [comment] 2019-06-09 14:53
I could reproduce the bug. It only seems to happen if you save inside of the city.

Please add all further bug reports in the official shadown rune repository: https://github.com/DelphiDie/TheShadowRune/issues

@DelphiDie could you have a look at this.

**Comment by NPBruce** [comment] 2019-08-08 10:36
Looks like this was caused by a change to the ini reader to treat '#' as a comment. Typically ';' is a comment in ini files so I'm looking into why this is changed.

**Comment by NPBruce** [comment] 2019-08-08 10:46
Fixed in 2.4, but unfortunately not for existing saves. I haven't addressed the underlying behaviour, so other odd places may break due to the '#' comment.

**Closed by NPBruce** 2019-08-08 10:46 UTC
