### ISSUE TITLE
Bug on Amnesia setting investigator as dead

### ISSUE THREAD

**Issue by renancarlosdev** [NPBruce/valkyrie#1070] opened 2019-02-17 15:47 UTC
### Description of Problem or Question
I was playing Amnesia scenario and one investigator died, I set it and the game didn't end on next turn

There was one question mark token(interaction token?) that didn't work too, next to the female npc on the kitchen after she left the room.

### Valkyrie Version
2.1.2

**Comment by redwolf2** [comment] 2019-02-17 16:35
I've also seen this in V2.2.00b.

**Comment by scrubbless** [comment] 2019-02-17 16:41
Eliminated trigger worked fine with a strain on reality in 2.200b Android

![screenshot_20190217-163850_valkyrie](https://user-images.githubusercontent.com/32058089/52916017-b902cc00-32d2-11e9-8675-6e6d9381a529.jpg)


I think this may just be an issue with Amnesia

**Comment by BenRQ** [comment] 2019-02-17 19:23
Related to #946  
It would be interesting to know what is done in the Amnesia scenario to understand if it's a bug in Valkyrie or if it was done on purpose in the scenario.

**Comment by scrubbless** [comment] 2019-02-17 19:55
Hi @BenRQ 

Its not a bug with Valkyrie from what I can see. Having a look at the Events.ini there are no events that have the "trigger=Eliminated" trigger.

**Comment by BenRQ** [comment] 2019-02-17 19:59
Well in that case, shouldn't we end the scenario automatically ?
This is what I suggested in #946 but I understood from you answer that it was already implemented.

**Comment by BenRQ** [comment] 2019-02-17 20:02
We should also ping the author @drinkinguranus so he can fix the scenario.

**Comment by scrubbless** [comment] 2019-02-17 20:10
The Author has to create an event that triggers from "Eliminated" to place an outro in this situation. Nothing wrong on the valkyrie side here. 

I am not sure how it would interact if Valkyrie intervened here. I wouldn't change it to do that personally.

I had an idea that could take advantage of this functionality, for example. If an investigator is eliminated, you could actually give the party an "extra life", by say spawning a token which gives the player a new investigator (similar to the locked rooms in Left4Dead). 

I've been toying with the idea myself, as a way to crank up the severity of events to really make players feel hopeless. Having these "respawns" might be quite fun.

**Comment by antontimmermans** [comment] 2019-03-07 15:46
I agree that this should be solved in the scenario itself. Not in Valkyrie.
I will also add some tips in the tutorial on how to end a scenario including: sad endings (like investigator died, scenario loss), the almost won endings and ofcourse the happy endings (yes, I said it). created a ticket for it to later work on it: https://github.com/scrubbless/MoM2ndTutorial/issues/19

**Comment by BenRQ** [comment] 2019-03-27 01:02
I'm closing this issue.
Please raise your hand if you think it should be reopened :)

**Closed by BenRQ** 2019-03-27 01:02 UTC
Labels: Scenario, bug

**Comment by scrubbless** [comment] 2019-03-27 08:18
I'd leave it closed its and old thread and a fix the author needs to do. People can still comment on closed threads
